# **3.1. GaussianNB() + SelectKBest**

# **0.4814    7_признаков**

In [21]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [26]:
lst_1 = list(range(1,10))
lst_2 = list(range(2,9))
lst_3 = list(range(1,5))
k = []

In [27]:
# максимальное значение: n_splits: 4 KBest: 7 0.4658693111317712
model=GaussianNB()
for i in lst_2:
   kfold=KFold(n_splits=i,random_state=7,shuffle=True)
   for j in lst_1:
      test=SelectKBest(score_func=f_classif, k=j)
      fit=test.fit(X,Y)
      features=fit.transform(X)
      results=cross_val_score(model, features, Y, cv=kfold)
      res = results.mean()
      k.append(res)
      print(f'n_splits: {i} KBest: {j} {res}')
   print(f'i {i} max: {max(k)}')

n_splits: 2 KBest: 1 0.4006002491005403
n_splits: 2 KBest: 2 0.40615179465125384
n_splits: 2 KBest: 3 0.42265605612181867
n_splits: 2 KBest: 4 0.4414108127499424
n_splits: 2 KBest: 5 0.45731532937207287
n_splits: 2 KBest: 6 0.4631668599032772
n_splits: 2 KBest: 7 0.4657165296361569
n_splits: 2 KBest: 8 0.4583649841574794
n_splits: 2 KBest: 9 0.45881511920699874
i 2 max: 0.4657165296361569
n_splits: 3 KBest: 1 0.40060151895423673
n_splits: 3 KBest: 2 0.406603875155638
n_splits: 3 KBest: 3 0.42115647854744953
n_splits: 3 KBest: 4 0.44411262377926225
n_splits: 3 KBest: 5 0.4589666080520704
n_splits: 3 KBest: 6 0.46301768853157266
n_splits: 3 KBest: 7 0.46391690046987594
n_splits: 3 KBest: 8 0.4612170357062721
n_splits: 3 KBest: 9 0.4619668405381736
i 3 max: 0.4657165296361569
n_splits: 4 KBest: 1 0.4006041828849116
n_splits: 4 KBest: 2 0.40555598364120693
n_splits: 4 KBest: 3 0.4219093756278756
n_splits: 4 KBest: 4 0.4436639382807712
n_splits: 4 KBest: 5 0.4582167900153463
n_splits: 4 KBe

**Вывод: отбор показал, что лучший результат дает выбор 7 лучших признаков**

In [96]:
test=SelectKBest(score_func=f_classif, k=6)
fit=test.fit(X,Y)
features=fit.transform(X)
fit.scores_

array([  4.70368846, 496.43200214, 418.45793796, 354.51376472,
        53.09011086,  20.75182914, 364.22358787,  92.0107774 ,
        33.2485345 ])

In [28]:
model=model=GaussianNB()

In [29]:
model.fit(X,Y)

GaussianNB()

In [30]:
x_new=np.array([[1,0.0,22,0.0,2.0,1.0,3,4.0,4.0	],[0,0.0,26,1.0,4.0,1.0,3,3.0,6.0	]])
# первый = 4, второй = 1

In [31]:
model.predict(x_new)

array([4., 4.])

In [32]:
model.predict_proba(x_new)

array([[0.05068993, 0.01073339, 0.00197263, 0.93660405],
       [0.24733388, 0.09819985, 0.06405634, 0.59040993]])

Вывод:
лучшими 7-ю признаками будут: **'Семейное_положение', 'Возраст', 'Высшее_образование', 'Профессия', 'Уровень_расходов', 'Размер_семьи', 'Анонимная_категория'**

============================================================================================

In [33]:
from sklearn.preprocessing import StandardScaler

In [34]:
scaler=StandardScaler().fit(X)

In [35]:
rescaledX=scaler.transform(X)

In [36]:
X = rescaledX

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3)

In [23]:
from sklearn.naive_bayes import GaussianNB

In [39]:
model = GaussianNB()

In [40]:
model.fit(x_train, y_train)

GaussianNB()

In [41]:
predictions = model.predict(x_test)

In [42]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [15]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         1.0       0.38      0.36      0.37       498
         2.0       0.32      0.26      0.28       480
         3.0       0.48      0.53      0.51       495
         4.0       0.56      0.62      0.59       527

    accuracy                           0.45      2000
   macro avg       0.43      0.44      0.44      2000
weighted avg       0.44      0.45      0.44      2000



In [43]:
print(confusion_matrix(y_test, predictions))

[[135  68 128 120]
 [ 89  76 238  84]
 [ 41  45 348  89]
 [ 73  36  36 394]]


=======================================================================

===========================================================================================================

================================================================

# **3. Учим, проверяем модель**

In [76]:
model = GaussianNB()

In [77]:
model.fit(X,Y)

GaussianNB()

In [78]:
predictions = model.predict(XX)

In [79]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [80]:
print(classification_report(YY, predictions))

              precision    recall  f1-score   support

         1.0       0.39      0.24      0.30      1616
         2.0       0.34      0.17      0.23      1572
         3.0       0.47      0.66      0.55      1720
         4.0       0.52      0.74      0.62      1757

    accuracy                           0.46      6665
   macro avg       0.43      0.45      0.42      6665
weighted avg       0.43      0.46      0.43      6665



In [81]:
print(confusion_matrix(YY, predictions))

[[ 383  226  423  584]
 [ 276  267  714  315]
 [ 125  175 1136  284]
 [ 196  117  137 1307]]


In [82]:
x_new = XX[1000:1020]

In [83]:
YY[1000:1020]

array([2., 3., 2., 3., 3., 2., 2., 2., 2., 3., 4., 1., 3., 2., 3., 1., 1.,
       4., 4., 3.])

==========================================

In [84]:
res = model.predict(x_new)
print(res)

[1. 3. 3. 3. 4. 3. 4. 4. 3. 2. 4. 4. 3. 4. 4. 4. 3. 4. 2. 2.]


In [ ]:
========================================================================================================================

# **GrideSearchCV**

In [19]:
from sklearn.model_selection import GridSearchCV

In [20]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, shuffle=True, random_state=7) 

In [22]:
clf = KNeighborsClassifier()

In [64]:
grid_params = {
               'n_neighbors':np.arange(2,120,3),
               'weights':['uniform','distance'],
               'metric':['euclidean','manhattan']}

In [65]:
grid = GridSearchCV(clf, grid_params, cv=3,verbose=1,n_jobs=-1)
grid.fit(X_train,Y_train)

Fitting 3 folds for each of 160 candidates, totalling 480 fits


GridSearchCV(cv=3, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': array([  2,   5,   8,  11,  14,  17,  20,  23,  26,  29,  32,  35,  38,
        41,  44,  47,  50,  53,  56,  59,  62,  65,  68,  71,  74,  77,
        80,  83,  86,  89,  92,  95,  98, 101, 104, 107, 110, 113, 116,
       119]),
                         'weights': ['uniform', 'distance']},
             verbose=1)

In [66]:
print(grid.best_params_)
print(grid.best_estimator_)

{'metric': 'manhattan', 'n_neighbors': 62, 'weights': 'uniform'}
KNeighborsClassifier(metric='manhattan', n_neighbors=62)


In [67]:
from sklearn.metrics import classification_report, confusion_matrix

In [68]:
grid_predictions = grid.predict(XX)
print(classification_report(YY, grid_predictions))

              precision    recall  f1-score   support

         1.0       0.46      0.43      0.44      1616
         2.0       0.40      0.21      0.28      1572
         3.0       0.51      0.66      0.58      1720
         4.0       0.59      0.70      0.64      1757

    accuracy                           0.51      6665
   macro avg       0.49      0.50      0.48      6665
weighted avg       0.49      0.51      0.49      6665



In [69]:
print(confusion_matrix(YY, grid_predictions))

[[ 687  236  306  387]
 [ 324  334  701  213]
 [ 165  168 1143  244]
 [ 309  107  104 1237]]


In [ ]:
================================================================================================================

In [117]:
model = KNeighborsClassifier(n_neighbors = 2,weights='distance')

In [118]:
model.fit(X,Y)

KNeighborsClassifier(n_neighbors=2, weights='distance')

In [119]:
new_predictions = model.predict(XX)

In [120]:
print(classification_report(YY, new_predictions))
print(confusion_matrix(YY, new_predictions))

              precision    recall  f1-score   support

         1.0       0.91      0.99      0.95      1616
         2.0       0.91      0.94      0.93      1572
         3.0       0.97      0.90      0.94      1720
         4.0       1.00      0.96      0.98      1757

    accuracy                           0.95      6665
   macro avg       0.95      0.95      0.95      6665
weighted avg       0.95      0.95      0.95      6665

[[1604    6    5    1]
 [  81 1483    7    1]
 [  47  119 1553    1]
 [  23   17   36 1681]]


In [9]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
# отбор признаков:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
# ансамблевые функции:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
import numpy as np
from sklearn.linear_model import RidgeClassifier
from sklearn.model_selection import GridSearchCV
from scipy.stats import uniform
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import train_test_split
# сохраняет параметры после перезагрузки:
import pickle
import joblib

# **GrideSearchCV**

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import GaussianNB

In [11]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, shuffle=True, random_state=7) 

In [12]:
clf = GaussianNB()

In [15]:
parametrs = {
 'var_smoothing': np.logspace(0,-9, num =100)
}

In [16]:
grid = GridSearchCV(clf, param_grid=parametrs, cv=3,verbose=1,n_jobs=-1)
grid.fit(X,Y)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


GridSearchCV(cv=3, estimator=GaussianNB(), n_jobs=-1,
             param_grid={'var_smoothing': array([1.00000000e+00, 8.11130831e-01, 6.57933225e-01, 5.33669923e-01,
       4.32876128e-01, 3.51119173e-01, 2.84803587e-01, 2.31012970e-01,
       1.87381742e-01, 1.51991108e-01, 1.23284674e-01, 1.00000000e-01,
       8.11130831e-02, 6.57933225e-02, 5.33669923e-02, 4.32876128e-02,
       3.51119173e-02, 2.8480358...
       1.23284674e-07, 1.00000000e-07, 8.11130831e-08, 6.57933225e-08,
       5.33669923e-08, 4.32876128e-08, 3.51119173e-08, 2.84803587e-08,
       2.31012970e-08, 1.87381742e-08, 1.51991108e-08, 1.23284674e-08,
       1.00000000e-08, 8.11130831e-09, 6.57933225e-09, 5.33669923e-09,
       4.32876128e-09, 3.51119173e-09, 2.84803587e-09, 2.31012970e-09,
       1.87381742e-09, 1.51991108e-09, 1.23284674e-09, 1.00000000e-09])},
             verbose=1)

In [17]:
print(grid.best_params_)
print(grid.best_estimator_)

{'var_smoothing': 3.511191734215127e-05}
GaussianNB(var_smoothing=3.511191734215127e-05)


In [21]:
from sklearn.metrics import classification_report, confusion_matrix

In [19]:
grid_predictions = grid.predict(X_test)
print(classification_report(Y_test, grid_predictions))

              precision    recall  f1-score   support

         1.0       0.41      0.28      0.33       351
         2.0       0.33      0.20      0.25       347
         3.0       0.45      0.59      0.51       361
         4.0       0.52      0.72      0.61       373

    accuracy                           0.45      1432
   macro avg       0.43      0.45      0.42      1432
weighted avg       0.43      0.45      0.43      1432



In [22]:
print(confusion_matrix(Y_test, grid_predictions))

[[ 97  55  85 114]
 [ 64  70 149  64]
 [ 38  43 212  68]
 [ 37  44  23 269]]


In [ ]:
================================================================================================================

In [25]:
model = GaussianNB(var_smoothing=3.511191734215127e-05)

In [26]:
model.fit(X,Y)

GaussianNB(var_smoothing=3.511191734215127e-05)

In [27]:
new_predictions = model.predict(X_test)

In [28]:
print(classification_report(Y_test, new_predictions))
print(confusion_matrix(Y_test, new_predictions))

              precision    recall  f1-score   support

         1.0       0.41      0.28      0.33       351
         2.0       0.33      0.20      0.25       347
         3.0       0.45      0.59      0.51       361
         4.0       0.52      0.72      0.61       373

    accuracy                           0.45      1432
   macro avg       0.43      0.45      0.42      1432
weighted avg       0.43      0.45      0.43      1432

[[ 97  55  85 114]
 [ 64  70 149  64]
 [ 38  43 212  68]
 [ 37  44  23 269]]


In [29]:
kfold=KFold(n_splits=3,random_state=7,shuffle=True)
results=cross_val_score(model, X, Y, cv=3)
results.mean()

0.44211629125196444

In [ ]:
================================================================================================================

=========================================