# **3. LogisticRegression + SelectKBest**

In [16]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [17]:
lst_1 = list(range(1,10))
lst_2 = list(range(2,9))
k = []

In [9]:
model=LogisticRegression(solver='newton-cg',class_weight= 'balanced')    # максимальное значение: n_splits: 6 KBest: 7 0.4814692280038815
for i in lst_2:
   kfold=KFold(n_splits=i,random_state=7,shuffle=True)
   for j in lst_1:
      test=SelectKBest(score_func=f_classif, k=j)
      fit=test.fit(X,Y)
      features=fit.transform(X)
      results=cross_val_score(model, features, Y, cv=kfold)
      res = results.mean()
      k.append(res)
      print(f'n_splits: {i} KBest: {j} {res}')
   print(f'i {i} max: {max(k)}')

n_splits: 2 KBest: 1 0.4006002491005403
n_splits: 2 KBest: 2 0.4174037301689353
n_splits: 2 KBest: 3 0.44831082748130757
n_splits: 2 KBest: 4 0.4715667545145871
n_splits: 2 KBest: 5 0.47006682961213286
n_splits: 2 KBest: 6 0.4789192904884726
n_splits: 2 KBest: 7 0.47846866019134926
n_splits: 2 KBest: 8 0.4780190654119434
n_splits: 2 KBest: 9 0.4778687802753865
i 2 max: 0.4789192904884726
n_splits: 3 KBest: 1 0.40060151895423673
n_splits: 3 KBest: 2 0.4201060358174493
n_splits: 3 KBest: 3 0.44906143023127165
n_splits: 3 KBest: 4 0.47531871602288556
n_splits: 3 KBest: 5 0.4702180708840808
n_splits: 3 KBest: 6 0.47696894858328703
n_splits: 3 KBest: 7 0.48131958625849075
n_splits: 3 KBest: 8 0.4765185658592874
n_splits: 3 KBest: 9 0.4798188283483909
i 3 max: 0.48131958625849075
n_splits: 4 KBest: 1 0.4006041828849116
n_splits: 4 KBest: 2 0.41965856528574236
n_splits: 4 KBest: 3 0.4499642088389045
n_splits: 4 KBest: 4 0.47442093214010256
n_splits: 4 KBest: 5 0.46766832107768125
n_splits: 4 

**Вывод: отбор показал, что лучший результат дает выбор 7 лучших признаков**

In [18]:
test=SelectKBest(score_func=f_classif, k=7)
fit=test.fit(X,Y)
features=fit.transform(X)
fit.scores_

array([  4.70368846, 496.43200214, 418.45793796, 354.51376472,
        53.09011086,  20.75182914, 364.22358787,  92.0107774 ,
        33.2485345 ])

Вывод:
лучшими 7-ю признаками будут: **'Семейное_положение', 'Возраст', 'Высшее_образование', 'Профессия', 'Уровень_расходов', 'Размер_семьи', 'Анонимная_категория'**

# **3.1 RandomForestClassifier() + SelectKBest**

In [20]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

In [21]:
lst_1 = list(range(1,10))
lst_2 = list(range(2,9))
k = []

In [22]:
model=RandomForestClassifier()    
for i in lst_2:
   kfold=KFold(n_splits=i,random_state=7,shuffle=True)
   for j in lst_1:
      test=SelectKBest(score_func=f_classif, k=j)
      fit=test.fit(X,Y)
      features=fit.transform(X)
      results=cross_val_score(model, features, Y, cv=kfold)
      res = results.mean()
      k.append(res)
      print(f'n_splits: {i} KBest: {j} {res}')
   print(f'i {i} max: {max(k)}')

n_splits: 2 KBest: 1 0.4006002491005403
n_splits: 2 KBest: 2 0.4456105124317954
n_splits: 2 KBest: 3 0.4618149690119072
n_splits: 2 KBest: 4 0.46301612454162583
n_splits: 2 KBest: 5 0.43480862191861447
n_splits: 2 KBest: 6 0.4579142187928277
n_splits: 2 KBest: 7 0.4666162594650822
n_splits: 2 KBest: 8 0.4802711363573332
n_splits: 2 KBest: 9 0.4934740322771773
i 2 max: 0.4934740322771773
n_splits: 3 KBest: 1 0.40060151895423673
n_splits: 3 KBest: 2 0.4465107699423702
n_splits: 3 KBest: 3 0.4556630359118758
n_splits: 3 KBest: 4 0.4688648963950875
n_splits: 3 KBest: 5 0.4432102372776674
n_splits: 3 KBest: 6 0.4738160668835907
n_splits: 3 KBest: 7 0.4694664423668842
n_splits: 3 KBest: 8 0.47891948132228807
n_splits: 3 KBest: 9 0.4868716272797924
i 3 max: 0.4934740322771773
n_splits: 4 KBest: 1 0.4006041828849116
n_splits: 4 KBest: 2 0.4504137587848577
n_splits: 4 KBest: 3 0.4571651095951278
n_splits: 4 KBest: 4 0.46961802117367646
n_splits: 4 KBest: 5 0.4418606074703426
n_splits: 4 KBest: 

**Вывод: отбор показал, что лучший результат дает выбор 7 лучших признаков**

In [30]:
test=SelectKBest(score_func=f_classif, k=6)
fit=test.fit(X,Y)
features=fit.transform(X)
fit.scores_

array([  4.70368846, 496.43200214, 418.45793796, 354.51376472,
        53.09011086,  20.75182914, 364.22358787,  92.0107774 ,
        33.2485345 ])

Вывод:
лучшими 7-ю признаками будут: **'Семейное_положение', 'Возраст', 'Высшее_образование', 'Профессия', 'Уровень_расходов', 'Размер_семьи', 'Анонимная_категория'**

# **4. LogisticRegression + рекурсивное_исключение**

In [10]:
from sklearn.feature_selection import RFE

In [11]:
lst_1 = list(range(1,10))
lst_2 = list(range(2,9))
k = []

In [12]:
model=LogisticRegression(solver='newton-cg',class_weight= 'balanced')    # максимальное значение: n_splits: 3 KBest: 9 0.4798188283483909
for i in lst_2:
   kfold=KFold(n_splits=i,random_state=7,shuffle=True)
   for j in lst_1:
      rfe=RFE(model,n_features_to_select=j)  
      fit=rfe.fit(X,Y)  
      features=fit.transform(X)
      results=cross_val_score(model, features, Y, cv=kfold)
      res = results.mean()
      k.append(res)
      print(f'n_splits: {i} KBest: {j} {res}')
   print(f'i {i} max: {max(k)}')

n_splits: 2 KBest: 1 0.4006002491005403
n_splits: 2 KBest: 2 0.43991057268992206
n_splits: 2 KBest: 3 0.44951130767338443
n_splits: 2 KBest: 4 0.4520622380365288
n_splits: 2 KBest: 5 0.463765344121447
n_splits: 2 KBest: 6 0.46571634954611907
n_splits: 2 KBest: 7 0.46481630455962764
n_splits: 2 KBest: 8 0.46916655951309416
n_splits: 2 KBest: 9 0.4778687802753865
i 2 max: 0.4778687802753865
n_splits: 3 KBest: 1 0.40060151895423673
n_splits: 3 KBest: 2 0.43631035773545834
n_splits: 3 KBest: 3 0.4504127810349698
n_splits: 3 KBest: 4 0.4556639815264732
n_splits: 3 KBest: 5 0.4660172455786777
n_splits: 3 KBest: 6 0.46466596231887936
n_splits: 3 KBest: 7 0.46961733543908196
n_splits: 3 KBest: 8 0.4694669151741829
n_splits: 3 KBest: 9 0.4798188283483909
i 3 max: 0.4798188283483909
n_splits: 4 KBest: 1 0.4006041828849116
n_splits: 4 KBest: 2 0.43646195730841825
n_splits: 4 KBest: 3 0.4501136387368385
n_splits: 4 KBest: 4 0.45776327927691773
n_splits: 4 KBest: 5 0.4643673606215131
n_splits: 4 KB

KeyboardInterrupt: 

**Вывод: отбор показал, что лучший результат дает выбор 9 лучших признаков**

In [69]:
model=LogisticRegression(solver='newton-cg',class_weight= 'balanced')
rfe=RFE(model,n_features_to_select=7)
fit=rfe.fit(X,Y)
fit.n_features_

7

In [70]:
fit.support_

array([ True,  True, False,  True,  True, False,  True,  True,  True])

In [71]:
fit.ranking_

array([1, 1, 3, 1, 1, 2, 1, 1, 1])

**Вывод:рекурсивное исключение показало, что лучший результат достигается когла учитываются все 9 признаков, 7 признаков на втором месте**

# **4.1 RandomForestClassifier() + рекурсивное_исключение**

In [32]:
from sklearn.feature_selection import RFE

In [36]:
lst_1 = list(range(1,10))
lst_2 = list(range(2,9))
k = []

In [38]:
model=model=RandomForestClassifier()  
for j in lst_1:
      rfe=RFE(model,n_features_to_select=j)  
      fit=rfe.fit(X,Y)  
      features=fit.transform(X)
      results=cross_val_score(model, features, Y, cv=7)
      res = results.mean()
      k.append(res)
      print(f'n_splits: {i} KBest: {j} {res}')
print(f'i {i} max: {max(k)}')

n_splits: 4 KBest: 1 0.43420741853929407
n_splits: 4 KBest: 2 0.4655635076695946
n_splits: 4 KBest: 3 0.41800754929463907
n_splits: 4 KBest: 4 0.4393115063444056
n_splits: 4 KBest: 5 0.4427580056156776
n_splits: 4 KBest: 6 0.47081781295939157
n_splits: 4 KBest: 7 0.4792184974724413
n_splits: 4 KBest: 8 0.48927236162040894
n_splits: 4 KBest: 9 0.49437314275132926
i 4 max: 0.49437314275132926


**Вывод: отбор показал, что лучший результат дает выбор 9 лучших признаков**

In [69]:
model=LogisticRegression(solver='newton-cg',class_weight= 'balanced')
rfe=RFE(model,n_features_to_select=7)
fit=rfe.fit(X,Y)
fit.n_features_

7

In [70]:
fit.support_

array([ True,  True, False,  True,  True, False,  True,  True,  True])

In [71]:
fit.ranking_

array([1, 1, 3, 1, 1, 2, 1, 1, 1])

# **5. RandomForestClassifier() + отбор_главных_компонент**

In [39]:
from sklearn.decomposition import PCA

In [40]:
lst_1 = list(range(1,10))
lst_2 = list(range(2,9))
k = []

In [42]:
model=model=model=RandomForestClassifier()  
for j in lst_1:
      pca=PCA(n_components=j)  
      fit=pca.fit(X)  
      features=pca.fit_transform(X)
      results=cross_val_score(model, features, Y, cv=7)
      res = results.mean()
      k.append(res)
      print(f'n_splits: {i} KBest: {j} {res}')
print(f'i {i} max: {max(k)}')

n_splits: 4 KBest: 1 0.3629405592247393
n_splits: 4 KBest: 2 0.3909959576695316
n_splits: 4 KBest: 3 0.44261361417599565
n_splits: 4 KBest: 4 0.4537141194358121
n_splits: 4 KBest: 5 0.47216709349007185
n_splits: 4 KBest: 6 0.4894199022736062
n_splits: 4 KBest: 7 0.49752471817688254
n_splits: 4 KBest: 8 0.49647351070543644
n_splits: 4 KBest: 9 0.48837200147635135
i 4 max: 0.49752471817688254


**Вывод: отбор показал, что лучший результат дает выбор 9 лучших признаков**

In [ ]:
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

In [153]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
# отбор признаков:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
# ансамблевые функции:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
import numpy as np
from sklearn.linear_model import RidgeClassifier
from sklearn.model_selection import GridSearchCV
from scipy.stats import uniform
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import train_test_split
# сохраняет параметры после перезагрузки:
import pickle
import joblib

# **GrideSearchCV**

In [154]:
from sklearn.model_selection import GridSearchCV

In [142]:
# X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, shuffle=True, random_state=7) 

In [155]:
clf = LogisticRegression(max_iter = 5000)

In [156]:
parametrs = {'penalty':['l1','l2','elasticnet', 'none'], 
             'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000]}

In [157]:
grid = GridSearchCV(clf, param_grid=parametrs, cv=3,verbose=1,n_jobs=-1)
grid.fit(X,Y)

Fitting 3 folds for each of 28 candidates, totalling 84 fits


D:\Programs\lib\site-packages\sklearn\model_selection\_search.py:922: UserWarning: One or more of the test scores are non-finite: [       nan 0.43384135        nan 0.44423967        nan 0.45010872
        nan 0.44423967        nan 0.44423959        nan 0.44423967
        nan 0.44474277        nan 0.44423967        nan 0.44423975
        nan 0.44423967        nan 0.44440734        nan 0.44423967
        nan 0.44390416        nan 0.44423967]
  warnings.warn(


GridSearchCV(cv=3, estimator=LogisticRegression(max_iter=5000), n_jobs=-1,
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000],
                         'penalty': ['l1', 'l2', 'elasticnet', 'none']},
             verbose=1)

In [158]:
print(grid.best_params_)
print(grid.best_estimator_)

{'C': 0.01, 'penalty': 'l2'}
LogisticRegression(C=0.01, max_iter=5000)


In [159]:
from sklearn.metrics import classification_report, confusion_matrix

In [160]:
grid_predictions = grid.predict(XX)
print(classification_report(YY, grid_predictions))

              precision    recall  f1-score   support

         1.0       0.32      0.24      0.27       674
         2.0       0.27      0.20      0.23       437
         3.0       0.25      0.39      0.30       363
         4.0       0.42      0.46      0.43       611

    accuracy                           0.32      2085
   macro avg       0.31      0.32      0.31      2085
weighted avg       0.32      0.32      0.32      2085



In [161]:
print(confusion_matrix(YY, grid_predictions))

[[162 104 178 230]
 [130  89 118 100]
 [ 82  76 142  63]
 [139  59 134 279]]


In [ ]:
================================================================================================================

In [162]:
model = LogisticRegression(C=0.01, max_iter=5000)

In [163]:
model.fit(X,Y)

LogisticRegression(C=0.01, max_iter=5000)

In [164]:
new_predictions = model.predict(XX)

In [165]:
print(classification_report(YY, new_predictions))
print(confusion_matrix(YY, new_predictions))

              precision    recall  f1-score   support

         1.0       0.32      0.24      0.27       674
         2.0       0.27      0.20      0.23       437
         3.0       0.25      0.39      0.30       363
         4.0       0.42      0.46      0.43       611

    accuracy                           0.32      2085
   macro avg       0.31      0.32      0.31      2085
weighted avg       0.32      0.32      0.32      2085

[[162 104 178 230]
 [130  89 118 100]
 [ 82  76 142  63]
 [139  59 134 279]]


In [ ]:
================================================================================================================