=====================================================

In [3]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
# отбор признаков:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
# ансамблевые функции:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
import numpy as np
from sklearn.linear_model import RidgeClassifier
from sklearn.model_selection import GridSearchCV
from scipy.stats import uniform
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import train_test_split
# сохраняет параметры после перезагрузки:
import pickle
import joblib

In [18]:
+++++++++++++++++++++++++++++++++++++++++++++++++++++

SyntaxError: invalid syntax (Temp/ipykernel_17880/441078461.py, line 1)

In [11]:
kfold = KFold(n_splits= 10, random_state = 7, shuffle=True)

In [12]:
cart = DecisionTreeClassifier() # модель решающего дерева

**деревья_решенией (Bagged Decision Trees)**

In [13]:
model = BaggingClassifier(base_estimator=cart, n_estimators = 100, random_state=7)

In [14]:
results = cross_val_score(model, X, Y, cv=kfold)

In [15]:
results.mean(), results.std()

(0.4903143023083053, 0.02540988443186073)

In [ ]:
=============================================================================================================

In [1]:
import pandas as pd
import numpy as np
from pandas import read_csv

In [2]:
df=read_csv('D:\Политех\Класиффикация\Сегментация_клиентов\Train_cleared_!!!!!!!!.csv')

In [3]:
df=df.filter(regex='^(?!.*Unnamed).*$')

In [4]:
df_T=read_csv('D:\Политех\Класиффикация\Сегментация_клиентов\Test_cleared_!!!!!!!!.csv')

In [5]:
df_T=df_T.filter(regex='^(?!.*Unnamed).*$')

**Обучающий_набор**

In [6]:
array = df.values
array
X = array[:,0:9]
Y = array[:,9]

**Тестовый_набор**

In [7]:
array_T = df_T.values
array_T
XX = array_T[:,0:9]
YY = array_T[:,9]

In [8]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
# отбор признаков:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
# ансамблевые функции:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
import numpy as np
from sklearn.linear_model import RidgeClassifier
from sklearn.model_selection import GridSearchCV
from scipy.stats import uniform
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import train_test_split
# сохраняет параметры после перезагрузки:
import pickle
import joblib

In [9]:
========================================================================================================================

SyntaxError: invalid syntax (Temp/ipykernel_16424/549940349.py, line 1)

# **GrideSearchCV**

In [14]:
from sklearn.model_selection import GridSearchCV
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsClassifier

In [15]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, shuffle=True, random_state=7) 

In [16]:
clf = BaggingClassifier()

In [17]:
params = {
          'bootstrap': [True, False],
          'bootstrap_features': [True, False],    
          'n_estimators': [5, 10, 15,100,1000],
          'max_samples' : [0.6, 0.8, 1.0],
          'base_estimator' : [DecisionTreeClassifier(criterion='entropy', max_depth=5), 
                              KNeighborsClassifier(metric='manhattan', n_neighbors=50)]
}

In [18]:
grid = GridSearchCV(clf, param_grid = params, cv=3,verbose=1,n_jobs=-1)

In [19]:
grid.fit(X_train,Y_train)

Fitting 3 folds for each of 120 candidates, totalling 360 fits


GridSearchCV(cv=3, estimator=BaggingClassifier(), n_jobs=-1,
             param_grid={'base_estimator': [DecisionTreeClassifier(criterion='entropy',
                                                                   max_depth=5),
                                            KNeighborsClassifier(metric='manhattan',
                                                                 n_neighbors=50)],
                         'bootstrap': [True, False],
                         'bootstrap_features': [True, False],
                         'max_samples': [0.6, 0.8, 1.0],
                         'n_estimators': [5, 10, 15, 100, 1000]},
             verbose=1)

In [20]:
print(grid.best_params_)
print(grid.best_estimator_)

BaggingClassifier(base_estimator=DecisionTreeClassifier(criterion='entropy',
                                                        max_depth=5),
                  bootstrap=False, bootstrap_features=True, n_estimators=100)


In [21]:
from sklearn.metrics import classification_report, confusion_matrix

In [22]:
grid_predictions = grid.predict(X_test)
print(classification_report(Y_test, grid_predictions))

              precision    recall  f1-score   support

         1.0       0.46      0.48      0.47       351
         2.0       0.42      0.28      0.34       347
         3.0       0.54      0.57      0.55       361
         4.0       0.59      0.71      0.64       373

    accuracy                           0.51      1432
   macro avg       0.50      0.51      0.50      1432
weighted avg       0.50      0.51      0.50      1432



In [23]:
print(confusion_matrix(Y_test, grid_predictions))

[[169  56  48  78]
 [ 86  97 118  46]
 [ 37  56 205  63]
 [ 77  22  10 264]]


In [132]:
kfold=KFold(n_splits=3,random_state=7,shuffle=True)
results=cross_val_score(model, X, Y, cv=3)
results.mean()

0.5105639951108784

In [ ]:
================================================================================================================

In [128]:
model = BaggingClassifier(base_estimator=DecisionTreeClassifier(criterion='entropy',max_depth=5),
                          bootstrap=False, 
                          bootstrap_features=True, 
                          max_samples=0.8,
                          n_estimators=100)

In [116]:
# model = BaggingClassifier(bootstrap_features=True, max_samples=0.6, n_estimators=1000)

In [129]:
model.fit(X_train,Y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(criterion='entropy',
                                                        max_depth=5),
                  bootstrap=False, bootstrap_features=True, max_samples=0.8,
                  n_estimators=100)

In [130]:
new_predictions = model.predict(X_test)

In [131]:
print(classification_report(Y_test, new_predictions))
print(confusion_matrix(Y_test, new_predictions))

              precision    recall  f1-score   support

         1.0       0.47      0.49      0.48       351
         2.0       0.41      0.31      0.35       347
         3.0       0.56      0.55      0.56       361
         4.0       0.59      0.71      0.65       373

    accuracy                           0.52      1432
   macro avg       0.51      0.52      0.51      1432
weighted avg       0.51      0.52      0.51      1432

[[172  61  40  78]
 [ 88 106 109  44]
 [ 39  59 200  63]
 [ 68  31   8 266]]


In [ ]:
================================================================================================================

# **Random Forest**

 **GridSearchCV**

**Поиск_лучших_параметров**

In [13]:
df.columns

Index(['Пол', 'Семейное_положение', 'Возраст', 'Высшее_образование',
       'Профессия', 'Опыт_работы', 'Уровень_расходов', 'Размер_семьи',
       'Анонимная_категория', 'Целевая_категория'],
      dtype='object')

In [14]:
from sklearn.model_selection import GridSearchCV

In [18]:
clf = RandomForestClassifier()

In [19]:
X_train = df.drop('Целевая_категория', axis=1)
y_train = df['Целевая_категория']

In [20]:
parametrs = { 'n_estimators': range (10, 250, 10),
              'max_depth': range (1,13, 2),
              'min_samples_leaf': range (1,8),
              'min_samples_split': range (2,10,2) }

In [21]:
grid = GridSearchCV(clf, parametrs, cv=5)
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_depth': range(1, 13, 2),
                         'min_samples_leaf': range(1, 8),
                         'min_samples_split': range(2, 10, 2),
                         'n_estimators': range(10, 51, 10)})

**Лучшие_параметры:**

In [32]:
grid.best_params_

{'max_depth': 9,
 'min_samples_leaf': 2,
 'min_samples_split': 2,
 'n_estimators': 90}

=================================================

In [33]:
lst_1 = list(range(6,10))
lst_2 = list(range(3,4))
lst_3 = list(range(100,200))
k = []

In [34]:
model = RandomForestClassifier(max_depth = 9, min_samples_leaf = 2, min_samples_split = 2, n_estimators= 90)
for i in lst_2:
   kfold=KFold(n_splits=i,random_state=7,shuffle=True)
   for j in lst_1:
      test=SelectKBest(score_func=f_classif, k=j)
      fit=test.fit(X,Y)
      features=fit.transform(X)
      results=cross_val_score(model, features, Y, cv=kfold)
      res = results.mean()
      k.append(res)
      print(f'n_splits: {i} KBest: {j} {res}')
   print(f'n_splits = {i} max = {max(k)}')

n_splits: 3 KBest: 6 0.5203278770020181
n_splits: 3 KBest: 7 0.5260301356565192
n_splits: 3 KBest: 8 0.5345825442517237
n_splits: 3 KBest: 9 0.5333824242397225
n_splits = 3 max = 0.5345825442517237


In [24]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
x_new = XX[1000:1020]
lst_1 = list(range(1,20))
lst_3 = list(range(50,200))
for i in lst_3:
 for j in lst_1:
  model=XGBClassifier(seed = 7, n_estimators = i, max_depth = j, learning_rate = 1,eval_metric='mlogloss')
  model.fit(X,Y)
  for k in x_new:
      predictions = model.predict(XX)
      print (f'n_estimators = {i} max_depth = {k}')
      print(confusion_matrix(YY, predictions))


D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


n_estimators = 50 max_depth = [ 0.  1. 38.  0.  3.  4.  3.  1.  6.]
[[ 777  241  337  261]
 [ 397  410  601  164]
 [ 178  207 1133  202]
 [ 355   97   74 1231]]
n_estimators = 50 max_depth = [ 1.  1. 48.  1.  1.  0.  2.  2.  6.]
[[ 777  241  337  261]
 [ 397  410  601  164]
 [ 178  207 1133  202]
 [ 355   97   74 1231]]
n_estimators = 50 max_depth = [ 0.  1. 51.  1.  1.  3.  3.  4.  6.]
[[ 777  241  337  261]
 [ 397  410  601  164]
 [ 178  207 1133  202]
 [ 355   97   74 1231]]
n_estimators = 50 max_depth = [ 1.  1. 73.  1.  1.  1.  1.  2.  2.]
[[ 777  241  337  261]
 [ 397  410  601  164]
 [ 178  207 1133  202]
 [ 355   97   74 1231]]
n_estimators = 50 max_depth = [ 1.  0. 30.  1.  2.  1.  3.  4.  6.]
[[ 777  241  337  261]
 [ 397  410  601  164]
 [ 178  207 1133  202]
 [ 355   97   74 1231]]
n_estimators = 50 max_depth = [ 0.  1. 65.  1.  6.  1.  2.  2.  6.]
[[ 777  241  337  261]
 [ 397  410  601  164]
 [ 178  207 1133  202]
 [ 355   97   74 1231]]
n_estimators = 50 max_depth = [ 0.

D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


n_estimators = 50 max_depth = [ 0.  1. 38.  0.  3.  4.  3.  1.  6.]
[[ 877  267  203  269]
 [ 368  586  446  172]
 [ 153  273 1088  206]
 [ 310   95   49 1303]]
n_estimators = 50 max_depth = [ 1.  1. 48.  1.  1.  0.  2.  2.  6.]
[[ 877  267  203  269]
 [ 368  586  446  172]
 [ 153  273 1088  206]
 [ 310   95   49 1303]]
n_estimators = 50 max_depth = [ 0.  1. 51.  1.  1.  3.  3.  4.  6.]
[[ 877  267  203  269]
 [ 368  586  446  172]
 [ 153  273 1088  206]
 [ 310   95   49 1303]]
n_estimators = 50 max_depth = [ 1.  1. 73.  1.  1.  1.  1.  2.  2.]
[[ 877  267  203  269]
 [ 368  586  446  172]
 [ 153  273 1088  206]
 [ 310   95   49 1303]]
n_estimators = 50 max_depth = [ 1.  0. 30.  1.  2.  1.  3.  4.  6.]
[[ 877  267  203  269]
 [ 368  586  446  172]
 [ 153  273 1088  206]
 [ 310   95   49 1303]]
n_estimators = 50 max_depth = [ 0.  1. 65.  1.  6.  1.  2.  2.  6.]
[[ 877  267  203  269]
 [ 368  586  446  172]
 [ 153  273 1088  206]
 [ 310   95   49 1303]]
n_estimators = 50 max_depth = [ 0.

D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


n_estimators = 50 max_depth = [ 0.  1. 38.  0.  3.  4.  3.  1.  6.]
[[ 932  268  170  246]
 [ 300  721  377  174]
 [ 145  257 1130  188]
 [ 268   83   44 1362]]
n_estimators = 50 max_depth = [ 1.  1. 48.  1.  1.  0.  2.  2.  6.]
[[ 932  268  170  246]
 [ 300  721  377  174]
 [ 145  257 1130  188]
 [ 268   83   44 1362]]
n_estimators = 50 max_depth = [ 0.  1. 51.  1.  1.  3.  3.  4.  6.]
[[ 932  268  170  246]
 [ 300  721  377  174]
 [ 145  257 1130  188]
 [ 268   83   44 1362]]
n_estimators = 50 max_depth = [ 1.  1. 73.  1.  1.  1.  1.  2.  2.]
[[ 932  268  170  246]
 [ 300  721  377  174]
 [ 145  257 1130  188]
 [ 268   83   44 1362]]
n_estimators = 50 max_depth = [ 1.  0. 30.  1.  2.  1.  3.  4.  6.]
[[ 932  268  170  246]
 [ 300  721  377  174]
 [ 145  257 1130  188]
 [ 268   83   44 1362]]
n_estimators = 50 max_depth = [ 0.  1. 65.  1.  6.  1.  2.  2.  6.]
[[ 932  268  170  246]
 [ 300  721  377  174]
 [ 145  257 1130  188]
 [ 268   83   44 1362]]
n_estimators = 50 max_depth = [ 0.

D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


n_estimators = 50 max_depth = [ 0.  1. 38.  0.  3.  4.  3.  1.  6.]
[[1067  209  154  186]
 [ 242  855  332  143]
 [ 125  218 1231  146]
 [ 203   56   41 1457]]
n_estimators = 50 max_depth = [ 1.  1. 48.  1.  1.  0.  2.  2.  6.]
[[1067  209  154  186]
 [ 242  855  332  143]
 [ 125  218 1231  146]
 [ 203   56   41 1457]]
n_estimators = 50 max_depth = [ 0.  1. 51.  1.  1.  3.  3.  4.  6.]
[[1067  209  154  186]
 [ 242  855  332  143]
 [ 125  218 1231  146]
 [ 203   56   41 1457]]
n_estimators = 50 max_depth = [ 1.  1. 73.  1.  1.  1.  1.  2.  2.]
[[1067  209  154  186]
 [ 242  855  332  143]
 [ 125  218 1231  146]
 [ 203   56   41 1457]]
n_estimators = 50 max_depth = [ 1.  0. 30.  1.  2.  1.  3.  4.  6.]
[[1067  209  154  186]
 [ 242  855  332  143]
 [ 125  218 1231  146]
 [ 203   56   41 1457]]
n_estimators = 50 max_depth = [ 0.  1. 65.  1.  6.  1.  2.  2.  6.]
[[1067  209  154  186]
 [ 242  855  332  143]
 [ 125  218 1231  146]
 [ 203   56   41 1457]]
n_estimators = 50 max_depth = [ 0.

D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


n_estimators = 50 max_depth = [ 0.  1. 38.  0.  3.  4.  3.  1.  6.]
[[1174  171  141  130]
 [ 166 1034  279   93]
 [  93  168 1344  115]
 [ 145   50   36 1526]]
n_estimators = 50 max_depth = [ 1.  1. 48.  1.  1.  0.  2.  2.  6.]
[[1174  171  141  130]
 [ 166 1034  279   93]
 [  93  168 1344  115]
 [ 145   50   36 1526]]
n_estimators = 50 max_depth = [ 0.  1. 51.  1.  1.  3.  3.  4.  6.]
[[1174  171  141  130]
 [ 166 1034  279   93]
 [  93  168 1344  115]
 [ 145   50   36 1526]]
n_estimators = 50 max_depth = [ 1.  1. 73.  1.  1.  1.  1.  2.  2.]
[[1174  171  141  130]
 [ 166 1034  279   93]
 [  93  168 1344  115]
 [ 145   50   36 1526]]
n_estimators = 50 max_depth = [ 1.  0. 30.  1.  2.  1.  3.  4.  6.]
[[1174  171  141  130]
 [ 166 1034  279   93]
 [  93  168 1344  115]
 [ 145   50   36 1526]]
n_estimators = 50 max_depth = [ 0.  1. 65.  1.  6.  1.  2.  2.  6.]
[[1174  171  141  130]
 [ 166 1034  279   93]
 [  93  168 1344  115]
 [ 145   50   36 1526]]
n_estimators = 50 max_depth = [ 0.

D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


n_estimators = 50 max_depth = [ 0.  1. 38.  0.  3.  4.  3.  1.  6.]
[[1334  124   99   59]
 [ 113 1171  226   62]
 [  64  119 1471   66]
 [  76   33   27 1621]]
n_estimators = 50 max_depth = [ 1.  1. 48.  1.  1.  0.  2.  2.  6.]
[[1334  124   99   59]
 [ 113 1171  226   62]
 [  64  119 1471   66]
 [  76   33   27 1621]]
n_estimators = 50 max_depth = [ 0.  1. 51.  1.  1.  3.  3.  4.  6.]
[[1334  124   99   59]
 [ 113 1171  226   62]
 [  64  119 1471   66]
 [  76   33   27 1621]]
n_estimators = 50 max_depth = [ 1.  1. 73.  1.  1.  1.  1.  2.  2.]
[[1334  124   99   59]
 [ 113 1171  226   62]
 [  64  119 1471   66]
 [  76   33   27 1621]]
n_estimators = 50 max_depth = [ 1.  0. 30.  1.  2.  1.  3.  4.  6.]
[[1334  124   99   59]
 [ 113 1171  226   62]
 [  64  119 1471   66]
 [  76   33   27 1621]]
n_estimators = 50 max_depth = [ 0.  1. 65.  1.  6.  1.  2.  2.  6.]
[[1334  124   99   59]
 [ 113 1171  226   62]
 [  64  119 1471   66]
 [  76   33   27 1621]]
n_estimators = 50 max_depth = [ 0.

D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


n_estimators = 50 max_depth = [ 0.  1. 38.  0.  3.  4.  3.  1.  6.]
[[1436   91   60   29]
 [  67 1305  166   34]
 [  30   88 1564   38]
 [  33   15   20 1689]]
n_estimators = 50 max_depth = [ 1.  1. 48.  1.  1.  0.  2.  2.  6.]
[[1436   91   60   29]
 [  67 1305  166   34]
 [  30   88 1564   38]
 [  33   15   20 1689]]
n_estimators = 50 max_depth = [ 0.  1. 51.  1.  1.  3.  3.  4.  6.]
[[1436   91   60   29]
 [  67 1305  166   34]
 [  30   88 1564   38]
 [  33   15   20 1689]]
n_estimators = 50 max_depth = [ 1.  1. 73.  1.  1.  1.  1.  2.  2.]
[[1436   91   60   29]
 [  67 1305  166   34]
 [  30   88 1564   38]
 [  33   15   20 1689]]
n_estimators = 50 max_depth = [ 1.  0. 30.  1.  2.  1.  3.  4.  6.]
[[1436   91   60   29]
 [  67 1305  166   34]
 [  30   88 1564   38]
 [  33   15   20 1689]]
n_estimators = 50 max_depth = [ 0.  1. 65.  1.  6.  1.  2.  2.  6.]
[[1436   91   60   29]
 [  67 1305  166   34]
 [  30   88 1564   38]
 [  33   15   20 1689]]
n_estimators = 50 max_depth = [ 0.

D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


n_estimators = 50 max_depth = [ 0.  1. 38.  0.  3.  4.  3.  1.  6.]
[[1512   50   41   13]
 [  54 1382  119   17]
 [  20   57 1615   28]
 [  18   11   12 1716]]
n_estimators = 50 max_depth = [ 1.  1. 48.  1.  1.  0.  2.  2.  6.]
[[1512   50   41   13]
 [  54 1382  119   17]
 [  20   57 1615   28]
 [  18   11   12 1716]]
n_estimators = 50 max_depth = [ 0.  1. 51.  1.  1.  3.  3.  4.  6.]
[[1512   50   41   13]
 [  54 1382  119   17]
 [  20   57 1615   28]
 [  18   11   12 1716]]
n_estimators = 50 max_depth = [ 1.  1. 73.  1.  1.  1.  1.  2.  2.]
[[1512   50   41   13]
 [  54 1382  119   17]
 [  20   57 1615   28]
 [  18   11   12 1716]]
n_estimators = 50 max_depth = [ 1.  0. 30.  1.  2.  1.  3.  4.  6.]
[[1512   50   41   13]
 [  54 1382  119   17]
 [  20   57 1615   28]
 [  18   11   12 1716]]
n_estimators = 50 max_depth = [ 0.  1. 65.  1.  6.  1.  2.  2.  6.]
[[1512   50   41   13]
 [  54 1382  119   17]
 [  20   57 1615   28]
 [  18   11   12 1716]]
n_estimators = 50 max_depth = [ 0.

D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


n_estimators = 50 max_depth = [ 0.  1. 38.  0.  3.  4.  3.  1.  6.]
[[1520   51   32   13]
 [  29 1447   85   11]
 [  10   48 1640   22]
 [  11    7   16 1723]]
n_estimators = 50 max_depth = [ 1.  1. 48.  1.  1.  0.  2.  2.  6.]
[[1520   51   32   13]
 [  29 1447   85   11]
 [  10   48 1640   22]
 [  11    7   16 1723]]
n_estimators = 50 max_depth = [ 0.  1. 51.  1.  1.  3.  3.  4.  6.]
[[1520   51   32   13]
 [  29 1447   85   11]
 [  10   48 1640   22]
 [  11    7   16 1723]]
n_estimators = 50 max_depth = [ 1.  1. 73.  1.  1.  1.  1.  2.  2.]
[[1520   51   32   13]
 [  29 1447   85   11]
 [  10   48 1640   22]
 [  11    7   16 1723]]
n_estimators = 50 max_depth = [ 1.  0. 30.  1.  2.  1.  3.  4.  6.]
[[1520   51   32   13]
 [  29 1447   85   11]
 [  10   48 1640   22]
 [  11    7   16 1723]]
n_estimators = 50 max_depth = [ 0.  1. 65.  1.  6.  1.  2.  2.  6.]
[[1520   51   32   13]
 [  29 1447   85   11]
 [  10   48 1640   22]
 [  11    7   16 1723]]
n_estimators = 50 max_depth = [ 0.

D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


n_estimators = 50 max_depth = [ 0.  1. 38.  0.  3.  4.  3.  1.  6.]
[[1534   44   27   11]
 [  37 1455   69   11]
 [  14   50 1635   21]
 [  12    7   15 1723]]
n_estimators = 50 max_depth = [ 1.  1. 48.  1.  1.  0.  2.  2.  6.]
[[1534   44   27   11]
 [  37 1455   69   11]
 [  14   50 1635   21]
 [  12    7   15 1723]]
n_estimators = 50 max_depth = [ 0.  1. 51.  1.  1.  3.  3.  4.  6.]
[[1534   44   27   11]
 [  37 1455   69   11]
 [  14   50 1635   21]
 [  12    7   15 1723]]
n_estimators = 50 max_depth = [ 1.  1. 73.  1.  1.  1.  1.  2.  2.]
[[1534   44   27   11]
 [  37 1455   69   11]
 [  14   50 1635   21]
 [  12    7   15 1723]]
n_estimators = 50 max_depth = [ 1.  0. 30.  1.  2.  1.  3.  4.  6.]
[[1534   44   27   11]
 [  37 1455   69   11]
 [  14   50 1635   21]
 [  12    7   15 1723]]
n_estimators = 50 max_depth = [ 0.  1. 65.  1.  6.  1.  2.  2.  6.]
[[1534   44   27   11]
 [  37 1455   69   11]
 [  14   50 1635   21]
 [  12    7   15 1723]]
n_estimators = 50 max_depth = [ 0.

D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


n_estimators = 50 max_depth = [ 0.  1. 38.  0.  3.  4.  3.  1.  6.]
[[1534   46   26   10]
 [  33 1457   74    8]
 [  14   43 1644   19]
 [  13    7   17 1720]]
n_estimators = 50 max_depth = [ 1.  1. 48.  1.  1.  0.  2.  2.  6.]
[[1534   46   26   10]
 [  33 1457   74    8]
 [  14   43 1644   19]
 [  13    7   17 1720]]
n_estimators = 50 max_depth = [ 0.  1. 51.  1.  1.  3.  3.  4.  6.]
[[1534   46   26   10]
 [  33 1457   74    8]
 [  14   43 1644   19]
 [  13    7   17 1720]]
n_estimators = 50 max_depth = [ 1.  1. 73.  1.  1.  1.  1.  2.  2.]
[[1534   46   26   10]
 [  33 1457   74    8]
 [  14   43 1644   19]
 [  13    7   17 1720]]
n_estimators = 50 max_depth = [ 1.  0. 30.  1.  2.  1.  3.  4.  6.]
[[1534   46   26   10]
 [  33 1457   74    8]
 [  14   43 1644   19]
 [  13    7   17 1720]]
n_estimators = 50 max_depth = [ 0.  1. 65.  1.  6.  1.  2.  2.  6.]
[[1534   46   26   10]
 [  33 1457   74    8]
 [  14   43 1644   19]
 [  13    7   17 1720]]
n_estimators = 50 max_depth = [ 0.

D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


n_estimators = 50 max_depth = [ 0.  1. 38.  0.  3.  4.  3.  1.  6.]
[[1526   52   26   12]
 [  26 1466   69   11]
 [  12   48 1637   23]
 [  11    7   12 1727]]
n_estimators = 50 max_depth = [ 1.  1. 48.  1.  1.  0.  2.  2.  6.]
[[1526   52   26   12]
 [  26 1466   69   11]
 [  12   48 1637   23]
 [  11    7   12 1727]]
n_estimators = 50 max_depth = [ 0.  1. 51.  1.  1.  3.  3.  4.  6.]
[[1526   52   26   12]
 [  26 1466   69   11]
 [  12   48 1637   23]
 [  11    7   12 1727]]
n_estimators = 50 max_depth = [ 1.  1. 73.  1.  1.  1.  1.  2.  2.]
[[1526   52   26   12]
 [  26 1466   69   11]
 [  12   48 1637   23]
 [  11    7   12 1727]]
n_estimators = 50 max_depth = [ 1.  0. 30.  1.  2.  1.  3.  4.  6.]
[[1526   52   26   12]
 [  26 1466   69   11]
 [  12   48 1637   23]
 [  11    7   12 1727]]
n_estimators = 50 max_depth = [ 0.  1. 65.  1.  6.  1.  2.  2.  6.]
[[1526   52   26   12]
 [  26 1466   69   11]
 [  12   48 1637   23]
 [  11    7   12 1727]]
n_estimators = 50 max_depth = [ 0.

D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


KeyboardInterrupt: 

In [35]:
YY[1000:1020]

array([2., 3., 2., 3., 3., 2., 2., 2., 2., 3., 4., 1., 3., 2., 3., 1., 1.,
       4., 4., 3.])

In [36]:
x_new = XX[1000:1020]
lst_1 = list(range(1,20))
lst_3 = list(range(50,200))

#k = []
for i in lst_3:
 for j in lst_1:
  model=RandomForestClassifier(max_depth = 9, min_samples_leaf = 2, min_samples_split = 2, n_estimators= 90)
  model.fit(X,Y)
  res = model.predict(x_new)
  print(f'n_estimators:{i} глубина: {j} предсказание: {res}')
#  k.append(res)

n_estimators:50 глубина: 1 предсказание: [1. 3. 3. 3. 4. 3. 2. 4. 2. 1. 4. 4. 3. 1. 4. 4. 3. 4. 4. 2.]
n_estimators:50 глубина: 2 предсказание: [1. 3. 3. 3. 4. 3. 2. 2. 2. 3. 4. 4. 3. 1. 4. 4. 3. 4. 4. 2.]
n_estimators:50 глубина: 3 предсказание: [1. 3. 3. 3. 4. 3. 1. 2. 2. 3. 4. 4. 3. 1. 4. 4. 3. 4. 4. 2.]
n_estimators:50 глубина: 4 предсказание: [1. 3. 2. 3. 4. 3. 2. 2. 2. 3. 4. 4. 3. 1. 4. 4. 3. 4. 4. 3.]
n_estimators:50 глубина: 5 предсказание: [1. 3. 3. 3. 4. 3. 2. 4. 2. 1. 4. 4. 3. 1. 4. 4. 3. 4. 4. 2.]
n_estimators:50 глубина: 6 предсказание: [1. 3. 3. 3. 4. 3. 2. 4. 2. 3. 4. 4. 3. 1. 4. 4. 3. 4. 4. 2.]
n_estimators:50 глубина: 7 предсказание: [1. 3. 3. 3. 4. 3. 2. 4. 2. 1. 4. 4. 3. 1. 4. 4. 3. 4. 4. 2.]
n_estimators:50 глубина: 8 предсказание: [1. 3. 3. 3. 4. 3. 1. 4. 2. 3. 4. 4. 3. 1. 4. 4. 3. 4. 4. 2.]
n_estimators:50 глубина: 9 предсказание: [1. 3. 3. 3. 4. 3. 2. 2. 2. 1. 4. 4. 3. 1. 4. 4. 3. 4. 4. 2.]
n_estimators:50 глубина: 10 предсказание: [1. 3. 3. 3. 4. 3. 2. 4. 2. 3. 

KeyboardInterrupt: 

In [32]:
kfold=KFold(n_splits=3,random_state=7,shuffle=True)

model=XGBClassifier(seed = 7, n_estimators = 50, max_depth = 12, learning_rate = 0.3,eval_metric='mlogloss')

results=cross_val_score(model, X, Y, cv=kfold)

model.fit(X,Y)

results.mean(),results.std()

D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is depre

KeyboardInterrupt: 

In [ ]:
=============================================================================================================

In [1]:
import pandas as pd
import numpy as np
from pandas import read_csv

In [2]:
df=read_csv('D:\Политех\Класиффикация\Сегментация_клиентов\Train_cleared_!!!!!!!!.csv')

In [3]:
df=df.filter(regex='^(?!.*Unnamed).*$')

In [4]:
df_T=read_csv('D:\Политех\Класиффикация\Сегментация_клиентов\Test_cleared_!!!!!!!!.csv')

In [5]:
df_T=df_T.filter(regex='^(?!.*Unnamed).*$')

**Обучающий_набор**

In [6]:
array = df.values
array
X = array[:,0:9]
Y = array[:,9]

**Тестовый_набор**

In [7]:
array_T = df_T.values
array_T
XX = array_T[:,0:9]
YY = array_T[:,9]

In [8]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
# отбор признаков:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
# ансамблевые функции:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
import numpy as np
from sklearn.linear_model import RidgeClassifier
from sklearn.model_selection import GridSearchCV
from scipy.stats import uniform
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import train_test_split
# сохраняет параметры после перезагрузки:
import pickle
import joblib

In [ ]:
========================================================================================================================

# **GrideSearchCV**

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor

In [11]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, shuffle=True, random_state=7) 

In [12]:
clf = RandomForestClassifier()

In [13]:
params = {'n_estimators': range (10, 250, 10),
          'max_depth': range (1,13, 2),
          'min_samples_leaf': range (1,8),
          'min_samples_split': range (2,10,2) }

In [14]:
grid = GridSearchCV(clf, param_grid = params, cv=3,verbose=1,n_jobs=-1)

In [15]:
grid.fit(X_train,Y_train)

Fitting 3 folds for each of 4032 candidates, totalling 12096 fits


GridSearchCV(cv=3, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_depth': range(1, 13, 2),
                         'min_samples_leaf': range(1, 8),
                         'min_samples_split': range(2, 10, 2),
                         'n_estimators': range(10, 250, 10)},
             verbose=1)

In [16]:
print(grid.best_params_)
print(grid.best_estimator_)

{'max_depth': 7, 'min_samples_leaf': 3, 'min_samples_split': 2, 'n_estimators': 60}
RandomForestClassifier(max_depth=7, min_samples_leaf=3, n_estimators=60)


In [17]:
from sklearn.metrics import classification_report, confusion_matrix

In [18]:
grid_predictions = grid.predict(X_test)
print(classification_report(Y_test, grid_predictions))

              precision    recall  f1-score   support

         1.0       0.46      0.48      0.47       351
         2.0       0.40      0.34      0.37       347
         3.0       0.56      0.53      0.55       361
         4.0       0.59      0.68      0.63       373

    accuracy                           0.51      1432
   macro avg       0.50      0.51      0.50      1432
weighted avg       0.51      0.51      0.51      1432



In [19]:
print(confusion_matrix(Y_test, grid_predictions))

[[169  73  39  70]
 [ 78 119 103  47]
 [ 32  78 192  59]
 [ 85  29   7 252]]


In [ ]:
================================================================================================================

In [20]:
model = RandomForestClassifier(max_depth=7, min_samples_leaf=3, n_estimators=60)

In [21]:
model.fit(X_train,Y_train)

RandomForestClassifier(max_depth=7, min_samples_leaf=3, n_estimators=60)

In [22]:
new_predictions = model.predict(X_test)

In [23]:
print(classification_report(Y_test, new_predictions))
print(confusion_matrix(Y_test, new_predictions))

              precision    recall  f1-score   support

         1.0       0.48      0.46      0.47       351
         2.0       0.41      0.37      0.39       347
         3.0       0.58      0.53      0.56       361
         4.0       0.58      0.69      0.63       373

    accuracy                           0.52      1432
   macro avg       0.51      0.52      0.51      1432
weighted avg       0.52      0.52      0.52      1432

[[163  72  39  77]
 [ 75 130  93  49]
 [ 27  83 193  58]
 [ 77  31   7 258]]


In [ ]:
================================================================================================================

In [24]:
kfold=KFold(n_splits=3,random_state=7,shuffle=True)
results=cross_val_score(model, X, Y, cv=3)
results.mean()

0.5112624410686224

# **Extra Trees**

In [22]:
lst_1 = list(range(6,10))
lst_2 = list(range(3,4))
lst_3 = list(range(100,200))
k = []

In [29]:
for s in lst_3:
 model = GradientBoostingClassifier(n_estimators = s, random_state = 7)
 for i in lst_2:
   kfold=KFold(n_splits=i,random_state=7,shuffle=True)
   for j in lst_1:
      test=SelectKBest(score_func=f_classif, k=j)
      fit=test.fit(X,Y)
      features=fit.transform(X)
      results=cross_val_score(model, features, Y, cv=kfold)
      res = results.mean()
      k.append(res)
      print(f'n_splits: {i} KBest: {j} {res}')
   print(f'n_estimators = {s} n_splits = {i} max = {max(k)}')

n_splits: 3 KBest: 6 0.5344321239868246
n_splits: 3 KBest: 7 0.5353330245226233


KeyboardInterrupt: 

In [ ]:
=============================================================================================================

In [1]:
import pandas as pd
import numpy as np
from pandas import read_csv

In [2]:
df=read_csv('D:\Политех\Класиффикация\Сегментация_клиентов\Train_cleared_!!!!!!!!.csv')

In [3]:
df=df.filter(regex='^(?!.*Unnamed).*$')

In [4]:
df_T=read_csv('D:\Политех\Класиффикация\Сегментация_клиентов\Test_cleared_!!!!!!!!.csv')

In [5]:
df_T=df_T.filter(regex='^(?!.*Unnamed).*$')

**Обучающий_набор**

In [6]:
array = df.values
array
X = array[:,0:9]
Y = array[:,9]

**Тестовый_набор**

In [7]:
array_T = df_T.values
array_T
XX = array_T[:,0:9]
YY = array_T[:,9]

In [ ]:
========================================================================================================================

# **GrideSearchCV**

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor

In [10]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, shuffle=True, random_state=7) 

In [11]:
clf = ExtraTreesClassifier()

In [55]:
params = { 'n_estimators': np.arange(40,80,4),
           'max_depth' : np.arange(1,40,4),
           'min_weight_fraction_leaf' : [0.001,0.0001]}

In [56]:
grid = GridSearchCV(clf, param_grid = params, cv=3,verbose=1,n_jobs=-1)

In [57]:
grid.fit(X_train,Y_train)

Fitting 3 folds for each of 200 candidates, totalling 600 fits


GridSearchCV(cv=3, estimator=ExtraTreesClassifier(), n_jobs=-1,
             param_grid={'max_depth': array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37]),
                         'min_weight_fraction_leaf': [0.001, 0.0001],
                         'n_estimators': array([40, 44, 48, 52, 56, 60, 64, 68, 72, 76])},
             verbose=1)

In [58]:
print(grid.best_params_)
print(grid.best_estimator_)

{'max_depth': 37, 'min_weight_fraction_leaf': 0.001, 'n_estimators': 52}
ExtraTreesClassifier(max_depth=37, min_weight_fraction_leaf=0.001,
                     n_estimators=52)


In [47]:
from sklearn.metrics import classification_report, confusion_matrix

In [48]:
grid_predictions = grid.predict(X_test)
print(classification_report(Y_test, grid_predictions))

              precision    recall  f1-score   support

         1.0       0.47      0.48      0.47       351
         2.0       0.40      0.31      0.35       347
         3.0       0.52      0.54      0.53       361
         4.0       0.58      0.68      0.62       373

    accuracy                           0.50      1432
   macro avg       0.49      0.50      0.49      1432
weighted avg       0.49      0.50      0.50      1432



In [49]:
print(confusion_matrix(Y_test, grid_predictions))

[[167  63  47  74]
 [ 79 106 117  45]
 [ 32  68 195  66]
 [ 80  27  13 253]]


In [ ]:
================================================================================================================

In [59]:
model = ExtraTreesClassifier(max_depth=37, 
                             min_weight_fraction_leaf=0.001,
                             n_estimators=52)

In [60]:
model.fit(X_train,Y_train)

ExtraTreesClassifier(max_depth=37, min_weight_fraction_leaf=0.001,
                     n_estimators=52)

In [61]:
new_predictions = model.predict(X_test)

In [62]:
print(classification_report(Y_test, new_predictions))
print(confusion_matrix(Y_test, new_predictions))

              precision    recall  f1-score   support

         1.0       0.49      0.47      0.48       351
         2.0       0.41      0.34      0.37       347
         3.0       0.54      0.54      0.54       361
         4.0       0.58      0.69      0.63       373

    accuracy                           0.51      1432
   macro avg       0.50      0.51      0.51      1432
weighted avg       0.51      0.51      0.51      1432

[[164  66  47  74]
 [ 69 119 111  48]
 [ 27  74 196  64]
 [ 77  29  10 257]]


In [ ]:
================================================================================================================

In [63]:
kfold=KFold(n_splits=3,random_state=7,shuffle=True)
results=cross_val_score(model, X, Y, cv=3)
results.mean()

0.4964204644665619

# **AdaBoostClassifier**

In [ ]:
+++++++++++++++++++++++++++++++++++++++++++++++++++++

In [34]:
lst_1 = list(range(6,10))
lst_2 = list(range(2,9))
lst_3 = list(range(100,200))
k = []

In [35]:
for s in lst_3:
 model=AdaBoostClassifier(n_estimators = s, random_state = 7)
 for i in lst_2:
   kfold=KFold(n_splits=i,random_state=7,shuffle=True)
   for j in lst_1:
      test=SelectKBest(score_func=f_classif, k=j)
      fit=test.fit(X,Y)
      features=fit.transform(X)
      results=cross_val_score(model, features, Y, cv=kfold)
      res = results.mean()
      k.append(res)
      print(f'n_splits: {i} KBest: {j} {res}')
   print(f'n_estimators = {s} n_splits = {i} max = {max(k)}')

n_splits: 2 KBest: 6 0.5032254575997815
n_splits: 2 KBest: 7 0.5084765229224003
n_splits: 2 KBest: 8 0.510577093123478
n_splits: 2 KBest: 9 0.5057763429404165
n_estimators = 100 n_splits = 2 max = 0.510577093123478
n_splits: 3 KBest: 6 0.5147783351050098
n_splits: 3 KBest: 7 0.5108767292758092
n_splits: 3 KBest: 8 0.5168784775821121
n_splits: 3 KBest: 9 0.5176290929408114
n_estimators = 100 n_splits = 3 max = 0.5176290929408114
n_splits: 4 KBest: 6 0.5074281062154916
n_splits: 4 KBest: 7 0.5105797267917365
n_splits: 4 KBest: 8 0.5141801771698482
n_splits: 4 KBest: 9 0.5099791266236549
n_estimators = 100 n_splits = 4 max = 0.5176290929408114
n_splits: 5 KBest: 6 0.5135783945986496
n_splits: 5 KBest: 7 0.5090772693173293
n_splits: 5 KBest: 8 0.5149287321830458
n_splits: 5 KBest: 9 0.5101275318829709
n_estimators = 100 n_splits = 5 max = 0.5176290929408114
n_splits: 6 KBest: 6 0.5129756218865128
n_splits: 6 KBest: 7 0.5128268232228628
n_splits: 6 KBest: 8 0.5162775737033163
n_splits: 6 KB

KeyboardInterrupt: 

In [ ]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
x_new = XX[1000:1020]
for s in lst_3:
 model=AdaBoostClassifier(n_estimators = s, random_state = 7)
 model.fit(X,Y)
 for j in x_new:
      predictions = model.predict(XX)
      print(confusion_matrix(YY, predictions))


# **GrideSearchCV**

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsClassifier

In [10]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, shuffle=True, random_state=7) 

In [11]:
clf = AdaBoostClassifier()

In [128]:
params = {'n_estimators':range(10,200,25),'learning_rate':np.linspace(0,1,10)}

In [129]:
grid = GridSearchCV(clf, param_grid = params, cv=3,verbose=1,n_jobs=-1)

In [130]:
grid.fit(X_train,Y_train)

Fitting 3 folds for each of 80 candidates, totalling 240 fits


D:\Programs\lib\site-packages\sklearn\model_selection\_search.py:922: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
        nan        nan 0.46821951 0.48335214 0.48404639 0.47845883
 0.47776294 0.47962677 0.47753082 0.48195468 0.47962628 0.47799344
 0.48102309 0.48381671 0.48032444 0.47962547 0.48079031 0.47659858
 0.48381704 0.47776294 0.48055721 0.48055803 0.47822833 0.47869388
 0.47450247 0.47706364 0.47264255 0.4789273  0.4793922  0.47939285
 0.47613401 0.47566716 0.47450328 0.4738048  0.48358345 0.48079162
 0.47822687 0.47659874 0.47915845 0.47450215 0.47217505 0.46844935
 0.47589961 0.47916105 0.47590156 0.48009134 0.47566765 0.47427051
 0.47427083 0.4735717  0.47869437 0.47706641 0.48125473 0.47659858
 0.48009118 0.47846013 0.47566781 0.47729625 0.47915829 0.48032379
 0.47497062 0.47357202 0.47753017 0.47543389 0.47403757 0.4733386
 0.47496607 0.47310582 0.47636662 0.47240994 0.47124509 0.47496981


GridSearchCV(cv=3, estimator=AdaBoostClassifier(), n_jobs=-1,
             param_grid={'learning_rate': array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
                         'n_estimators': range(10, 200, 25)},
             verbose=1)

In [131]:
print(grid.best_params_)
print(grid.best_estimator_)

{'learning_rate': 0.1111111111111111, 'n_estimators': 60}
AdaBoostClassifier(learning_rate=0.1111111111111111, n_estimators=60)


In [132]:
from sklearn.metrics import classification_report, confusion_matrix

In [133]:
grid_predictions = grid.predict(X_test)
print(classification_report(Y_test, grid_predictions))

              precision    recall  f1-score   support

         1.0       0.45      0.49      0.47       351
         2.0       0.42      0.25      0.32       347
         3.0       0.50      0.61      0.55       361
         4.0       0.60      0.64      0.62       373

    accuracy                           0.50      1432
   macro avg       0.49      0.50      0.49      1432
weighted avg       0.49      0.50      0.49      1432



In [134]:
print(confusion_matrix(Y_test, grid_predictions))

[[171  51  67  62]
 [ 78  88 139  42]
 [ 38  48 220  55]
 [ 97  23  14 239]]


In [ ]:
================================================================================================================

In [140]:
model = AdaBoostClassifier()

In [141]:
model.fit(X_train,Y_train)

AdaBoostClassifier()

In [142]:
new_predictions = model.predict(X_test)

In [143]:
print(classification_report(Y_test, new_predictions))
print(confusion_matrix(Y_test, new_predictions))

              precision    recall  f1-score   support

         1.0       0.42      0.44      0.43       351
         2.0       0.40      0.36      0.38       347
         3.0       0.49      0.49      0.49       361
         4.0       0.61      0.64      0.62       373

    accuracy                           0.48      1432
   macro avg       0.48      0.48      0.48      1432
weighted avg       0.48      0.48      0.48      1432

[[153  80  58  60]
 [ 79 125 106  37]
 [ 46  81 178  56]
 [ 90  24  22 237]]


In [ ]:
================================================================================================================

In [144]:
kfold=KFold(n_splits=3,random_state=7,shuffle=True)
results=cross_val_score(model, X, Y, cv=3)
results.mean()

0.4857691636109656

# **GradientBoostingClassifier**

**GrideSearchCV**

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsClassifier

In [10]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, shuffle=True, random_state=7) 

In [11]:
clf = GradientBoostingClassifier()

In [15]:
params = {
            "loss":["deviance"],
            "learning_rate": [0.01,  0.05,  0.1,  0.2],
            "min_samples_split": np.linspace(0.1, 0.5, 6),
            "min_samples_leaf": np.linspace(0.1, 0.5, 6),
            "max_depth":[3,5,8],
            "max_features":["log2","sqrt"],
            "criterion": ["friedman_mse",  "mae"],
            "subsample":[0.5,  0.8,  0.9,  1.0],
            "n_estimators":[10]
            }

In [16]:
grid = GridSearchCV(clf, param_grid = params, cv=3,verbose=1,n_jobs=-1)

In [17]:
grid.fit(X_train,Y_train)

Fitting 3 folds for each of 6912 candidates, totalling 20736 fits


GridSearchCV(cv=3, estimator=GradientBoostingClassifier(), n_jobs=-1,
             param_grid={'criterion': ['friedman_mse', 'mae'],
                         'learning_rate': [0.01, 0.05, 0.1, 0.2],
                         'loss': ['deviance'], 'max_depth': [3, 5, 8],
                         'max_features': ['log2', 'sqrt'],
                         'min_samples_leaf': array([0.1 , 0.18, 0.26, 0.34, 0.42, 0.5 ]),
                         'min_samples_split': array([0.1 , 0.18, 0.26, 0.34, 0.42, 0.5 ]),
                         'n_estimators': [10],
                         'subsample': [0.5, 0.8, 0.9, 1.0]},
             verbose=1)

In [18]:
print(grid.best_params_)
print(grid.best_estimator_)

{'criterion': 'friedman_mse', 'learning_rate': 0.2, 'loss': 'deviance', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 0.1, 'min_samples_split': 0.1, 'n_estimators': 10, 'subsample': 1.0}
GradientBoostingClassifier(learning_rate=0.2, max_depth=5, max_features='log2',
                           min_samples_leaf=0.1, min_samples_split=0.1,
                           n_estimators=10)


In [19]:
from sklearn.metrics import classification_report, confusion_matrix

In [20]:
grid_predictions = grid.predict(X_test)
print(classification_report(Y_test, grid_predictions))

              precision    recall  f1-score   support

         1.0       0.48      0.47      0.48       351
         2.0       0.41      0.36      0.38       347
         3.0       0.54      0.53      0.54       361
         4.0       0.60      0.70      0.64       373

    accuracy                           0.52      1432
   macro avg       0.51      0.51      0.51      1432
weighted avg       0.51      0.52      0.51      1432



In [21]:
print(confusion_matrix(Y_test, grid_predictions))

[[166  69  45  71]
 [ 73 124 106  44]
 [ 35  73 191  62]
 [ 69  34   9 261]]


In [ ]:
================================================================================================================

In [23]:
model = GradientBoostingClassifier(learning_rate=0.2, max_depth=5, max_features='log2',
                           min_samples_leaf=0.1, min_samples_split=0.1,
                           n_estimators=10)

In [28]:
model = GradientBoostingClassifier()

In [29]:
model.fit(X_train,Y_train)

GradientBoostingClassifier()

In [30]:
new_predictions = model.predict(X_test)

In [31]:
print(classification_report(Y_test, new_predictions))
print(confusion_matrix(Y_test, new_predictions))

              precision    recall  f1-score   support

         1.0       0.46      0.45      0.45       351
         2.0       0.41      0.38      0.39       347
         3.0       0.56      0.53      0.55       361
         4.0       0.60      0.69      0.64       373

    accuracy                           0.51      1432
   macro avg       0.51      0.51      0.51      1432
weighted avg       0.51      0.51      0.51      1432

[[157  83  40  71]
 [ 75 131  96  45]
 [ 38  73 193  57]
 [ 70  30  17 256]]


In [ ]:
================================================================================================================

In [32]:
kfold=KFold(n_splits=3,random_state=7,shuffle=True)
results=cross_val_score(model, X, Y, cv=3)
results.mean()

0.5128339444735462

In [1]:
(-2**2)

-4

# **XGBClassifier**

**GrideSearchCV**

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsClassifier

In [10]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, shuffle=True, random_state=7) 

In [11]:
clf = XGBClassifier()

In [17]:
params = {
            'max_depth': [3, 4, 5],
            'learning_rate': [0.1, 0.2, 0.3],
            'n_estimators': [50, 100, 150],
            'gamma': [0, 0.1, 0.2],
            'min_child_weight': [0, 0.5, 1],
            'max_delta_step': [0],
            'subsample': [0.7, 0.8, 0.9, 1],
            'colsample_bytree': [0.6, 0.8, 1],
            'colsample_bylevel': [1],
            'reg_alpha': [0,  1, 10],
            'reg_lambda': [0, 0.01, 1],
            'base_score': [0.5]
            }

In [20]:
params = {
            'max_depth': [3, 5],
            'learning_rate': [0.1, 0.3],
            'n_estimators': [50, 1150],
            'gamma': [0.1, 0.2],
            'min_child_weight': [0.5, 1],
            'max_delta_step': [0],
            'subsample': [0.7,  1],
            'colsample_bytree': [0.6,  1],
            'colsample_bylevel': [1],
            'reg_alpha': [0,  1, 10],
            'reg_lambda': [0.01, 1],
            'base_score': [0.5]
            }

In [21]:
grid = GridSearchCV(clf, param_grid = params, cv=3,verbose=1,n_jobs=-1)

In [22]:
grid.fit(X_train,Y_train)

Fitting 3 folds for each of 768 candidates, totalling 2304 fits


KeyboardInterrupt: 

In [18]:
print(grid.best_params_)
print(grid.best_estimator_)

{'criterion': 'friedman_mse', 'learning_rate': 0.2, 'loss': 'deviance', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 0.1, 'min_samples_split': 0.1, 'n_estimators': 10, 'subsample': 1.0}
GradientBoostingClassifier(learning_rate=0.2, max_depth=5, max_features='log2',
                           min_samples_leaf=0.1, min_samples_split=0.1,
                           n_estimators=10)


In [31]:
from sklearn.metrics import classification_report, confusion_matrix

In [20]:
grid_predictions = grid.predict(X_test)
print(classification_report(Y_test, grid_predictions))

              precision    recall  f1-score   support

         1.0       0.48      0.47      0.48       351
         2.0       0.41      0.36      0.38       347
         3.0       0.54      0.53      0.54       361
         4.0       0.60      0.70      0.64       373

    accuracy                           0.52      1432
   macro avg       0.51      0.51      0.51      1432
weighted avg       0.51      0.52      0.51      1432



In [21]:
print(confusion_matrix(Y_test, grid_predictions))

[[166  69  45  71]
 [ 73 124 106  44]
 [ 35  73 191  62]
 [ 69  34   9 261]]


In [ ]:
================================================================================================================

In [27]:
model = XGBClassifier(n_estimators = 50, random_state = 7)

In [28]:
model.fit(X_train,Y_train)

[20:43:10] WARNING: D:\bld\xgboost-split_1645118015404\work\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=50, n_jobs=12,
              num_parallel_tree=1, objective='multi:softprob', predictor='auto',
              random_state=7, reg_alpha=0, reg_lambda=1, scale_pos_weight=None,
              subsample=1, tree_method='exact', validate_parameters=1,
              verbosity=None)

In [29]:
new_predictions = model.predict(X_test)

In [32]:
print(classification_report(Y_test, new_predictions))
print(confusion_matrix(Y_test, new_predictions))

              precision    recall  f1-score   support

         1.0       0.45      0.45      0.45       351
         2.0       0.38      0.37      0.38       347
         3.0       0.54      0.49      0.52       361
         4.0       0.60      0.67      0.63       373

    accuracy                           0.50      1432
   macro avg       0.49      0.50      0.49      1432
weighted avg       0.50      0.50      0.50      1432

[[157  87  45  62]
 [ 78 130  94  45]
 [ 33  94 178  56]
 [ 82  30  12 249]]


In [ ]:
================================================================================================================

# **Voting(ансамбль)**

In [19]:
kfold = KFold(n_splits= 3, random_state = 7, shuffle=True)

In [20]:
estimators = []

In [21]:
estimators.append(('logistic', LogisticRegression(C=0.01, max_iter=5000)))

In [22]:
estimators.append(('cart', DecisionTreeClassifier(criterion='entropy', max_depth=5)))

In [23]:
estimators.append(('svm', SVC(C=100, gamma=0.001)))

In [24]:
estimators.append(('KNN', KNeighborsClassifier(metric='manhattan', n_neighbors=50)))

In [25]:
estimators

[('logistic', LogisticRegression(C=0.01, max_iter=5000)),
 ('cart', DecisionTreeClassifier(criterion='entropy', max_depth=5)),
 ('svm', SVC(C=100, gamma=0.001)),
 ('KNN', KNeighborsClassifier(metric='manhattan', n_neighbors=50))]

In [26]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler().fit(X)
rescaledX=scaler.transform(X)

In [27]:
ensemble = VotingClassifier(estimators)

In [28]:
results = cross_val_score(ensemble, rescaledX, Y, cv=kfold)

In [86]:
results.mean(), results.std()

(0.5077266168760054, 0.008761881023465708)

In [29]:
results.mean(), results.std()

(0.500524883645501, 0.0031628796847189148)

# **Настройка_алгоритмов**

In [90]:
X_train_test, X_val, Y_train_test, Y_val = train_test_split(X, Y, test_size=0.25, random_state= 7)

In [91]:
param_grid = {'alpha':uniform()}

In [92]:
model = RidgeClassifier()

In [93]:
rsearch = RandomizedSearchCV(estimator = model, param_distributions = param_grid, n_iter = 100, cv = 3, random_state = 7)

In [94]:
rsearch.fit(X_val,Y_val)

RandomizedSearchCV(cv=3, estimator=RidgeClassifier(), n_iter=100,
                   param_distributions={'alpha': <scipy.stats._distn_infrastructure.rv_frozen object at 0x00000174EB969190>},
                   random_state=7)

In [95]:
rsearch.best_score_

0.43910709270421505

In [96]:
rsearch.best_estimator_.alpha

0.07630828937395717

In [97]:
model = RidgeClassifier(alpha=rsearch.best_estimator_.alpha)

In [98]:
model.fit(X_test, Y_test)

RidgeClassifier(alpha=0.07630828937395717)

In [99]:
model.score(X_test, Y_test)

0.4912