In [1]:
import pandas as pd
import numpy as np
from pandas import read_csv

In [2]:
df=read_csv('D:\Политех\Класиффикация\Сегментация_клиентов\Train_cleared_dropna.csv')

In [3]:
df_T=read_csv('D:\Политех\Класиффикация\Сегментация_клиентов\TEST_cleared_dropna.csv')

In [6]:
df=df.filter(regex='^(?!.*Unnamed).*$')

In [7]:
df_T=df_T.filter(regex='^(?!.*Unnamed).*$')

================================================================

**Обучающий_набор**

In [8]:
array = df.values
array

array([[ 1.,  0., 22., ...,  4.,  4.,  4.],
       [ 0.,  1., 67., ...,  1.,  6.,  2.],
       [ 1.,  1., 67., ...,  2.,  6.,  2.],
       ...,
       [ 0.,  0., 33., ...,  1.,  6.,  4.],
       [ 0.,  0., 27., ...,  4.,  6.,  2.],
       [ 1.,  1., 37., ...,  3.,  4.,  2.]])

In [9]:
X = array[:,0:9]
Y = array[:,9]

In [8]:
X

array([[ 1.,  0., 22., ...,  3.,  4.,  4.],
       [ 0.,  1., 67., ...,  3.,  1.,  6.],
       [ 1.,  1., 67., ...,  1.,  2.,  6.],
       ...,
       [ 0.,  0., 33., ...,  3.,  1.,  6.],
       [ 0.,  0., 27., ...,  3.,  4.,  6.],
       [ 1.,  1., 37., ...,  2.,  3.,  4.]])

In [9]:
Y

array([4., 2., 2., ..., 4., 2., 2.])

==============================================================

**Тестовый_набор**

In [10]:
array_T = df.values
array_T

array([[ 1.,  0., 22., ...,  4.,  4.,  4.],
       [ 0.,  1., 67., ...,  1.,  6.,  2.],
       [ 1.,  1., 67., ...,  2.,  6.,  2.],
       ...,
       [ 0.,  0., 33., ...,  1.,  6.,  4.],
       [ 0.,  0., 27., ...,  4.,  6.,  2.],
       [ 1.,  1., 37., ...,  3.,  4.,  2.]])

In [11]:
XX = array_T[:,0:9]
YY = array_T[:,9]

In [12]:
XX

array([[ 1.,  0., 22., ...,  3.,  4.,  4.],
       [ 0.,  1., 67., ...,  3.,  1.,  6.],
       [ 1.,  1., 67., ...,  1.,  2.,  6.],
       ...,
       [ 0.,  0., 33., ...,  3.,  1.,  6.],
       [ 0.,  0., 27., ...,  3.,  4.,  6.],
       [ 1.,  1., 37., ...,  2.,  3.,  4.]])

In [13]:
YY

array([4., 2., 2., ..., 4., 2., 2.])

=====================================================

In [12]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
# отбор признаков:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
# ансамблевые функции:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
import numpy as np
from sklearn.linear_model import RidgeClassifier
from sklearn.model_selection import GridSearchCV
from scipy.stats import uniform
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import train_test_split
# сохраняет параметры после перезагрузки:
import pickle
import joblib

In [18]:
+++++++++++++++++++++++++++++++++++++++++++++++++++++

SyntaxError: invalid syntax (Temp/ipykernel_17880/441078461.py, line 1)

In [11]:
kfold = KFold(n_splits= 10, random_state = 7, shuffle=True)

In [12]:
cart = DecisionTreeClassifier() # модель решающего дерева

**случайный_лес (Random Forest)**

In [16]:
model = RandomForestClassifier(n_estimators = 100, max_features = 3)

In [17]:
results = cross_val_score(model, X, Y, cv=kfold)

In [18]:
results.mean(), results.std()

(0.49392083237660456, 0.01948562805393034)

=================================================

# **GridSearchCV**

**Поиск_лучших_параметров**

In [13]:
df.columns

Index(['Пол', 'Семейное_положение', 'Возраст', 'Высшее_образование',
       'Профессия', 'Опыт_работы', 'Уровень_расходов', 'Размер_семьи',
       'Анонимная_категория', 'Целевая_категория'],
      dtype='object')

In [14]:
from sklearn.model_selection import GridSearchCV

In [18]:
clf = RandomForestClassifier()

In [19]:
X_train = df.drop('Целевая_категория', axis=1)
y_train = df['Целевая_категория']

In [20]:
parametrs = { 'n_estimators': range (10, 250, 10),
              'max_depth': range (1,13, 2),
              'min_samples_leaf': range (1,8),
              'min_samples_split': range (2,10,2) }

In [21]:
grid = GridSearchCV(clf, parametrs, cv=5)
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_depth': range(1, 13, 2),
                         'min_samples_leaf': range(1, 8),
                         'min_samples_split': range(2, 10, 2),
                         'n_estimators': range(10, 51, 10)})

**Лучшие_параметры:**

In [32]:
grid.best_params_

{'max_depth': 9,
 'min_samples_leaf': 2,
 'min_samples_split': 2,
 'n_estimators': 90}

=================================================

In [33]:
lst_1 = list(range(6,10))
lst_2 = list(range(3,4))
lst_3 = list(range(100,200))
k = []

In [34]:
model = RandomForestClassifier(max_depth = 9, min_samples_leaf = 2, min_samples_split = 2, n_estimators= 90)
for i in lst_2:
   kfold=KFold(n_splits=i,random_state=7,shuffle=True)
   for j in lst_1:
      test=SelectKBest(score_func=f_classif, k=j)
      fit=test.fit(X,Y)
      features=fit.transform(X)
      results=cross_val_score(model, features, Y, cv=kfold)
      res = results.mean()
      k.append(res)
      print(f'n_splits: {i} KBest: {j} {res}')
   print(f'n_splits = {i} max = {max(k)}')

n_splits: 3 KBest: 6 0.5203278770020181
n_splits: 3 KBest: 7 0.5260301356565192
n_splits: 3 KBest: 8 0.5345825442517237
n_splits: 3 KBest: 9 0.5333824242397225
n_splits = 3 max = 0.5345825442517237


In [24]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
x_new = XX[1000:1020]
lst_1 = list(range(1,20))
lst_3 = list(range(50,200))
for i in lst_3:
 for j in lst_1:
  model=XGBClassifier(seed = 7, n_estimators = i, max_depth = j, learning_rate = 1,eval_metric='mlogloss')
  model.fit(X,Y)
  for k in x_new:
      predictions = model.predict(XX)
      print (f'n_estimators = {i} max_depth = {k}')
      print(confusion_matrix(YY, predictions))


D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


n_estimators = 50 max_depth = [ 0.  1. 38.  0.  3.  4.  3.  1.  6.]
[[ 777  241  337  261]
 [ 397  410  601  164]
 [ 178  207 1133  202]
 [ 355   97   74 1231]]
n_estimators = 50 max_depth = [ 1.  1. 48.  1.  1.  0.  2.  2.  6.]
[[ 777  241  337  261]
 [ 397  410  601  164]
 [ 178  207 1133  202]
 [ 355   97   74 1231]]
n_estimators = 50 max_depth = [ 0.  1. 51.  1.  1.  3.  3.  4.  6.]
[[ 777  241  337  261]
 [ 397  410  601  164]
 [ 178  207 1133  202]
 [ 355   97   74 1231]]
n_estimators = 50 max_depth = [ 1.  1. 73.  1.  1.  1.  1.  2.  2.]
[[ 777  241  337  261]
 [ 397  410  601  164]
 [ 178  207 1133  202]
 [ 355   97   74 1231]]
n_estimators = 50 max_depth = [ 1.  0. 30.  1.  2.  1.  3.  4.  6.]
[[ 777  241  337  261]
 [ 397  410  601  164]
 [ 178  207 1133  202]
 [ 355   97   74 1231]]
n_estimators = 50 max_depth = [ 0.  1. 65.  1.  6.  1.  2.  2.  6.]
[[ 777  241  337  261]
 [ 397  410  601  164]
 [ 178  207 1133  202]
 [ 355   97   74 1231]]
n_estimators = 50 max_depth = [ 0.

D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


n_estimators = 50 max_depth = [ 0.  1. 38.  0.  3.  4.  3.  1.  6.]
[[ 877  267  203  269]
 [ 368  586  446  172]
 [ 153  273 1088  206]
 [ 310   95   49 1303]]
n_estimators = 50 max_depth = [ 1.  1. 48.  1.  1.  0.  2.  2.  6.]
[[ 877  267  203  269]
 [ 368  586  446  172]
 [ 153  273 1088  206]
 [ 310   95   49 1303]]
n_estimators = 50 max_depth = [ 0.  1. 51.  1.  1.  3.  3.  4.  6.]
[[ 877  267  203  269]
 [ 368  586  446  172]
 [ 153  273 1088  206]
 [ 310   95   49 1303]]
n_estimators = 50 max_depth = [ 1.  1. 73.  1.  1.  1.  1.  2.  2.]
[[ 877  267  203  269]
 [ 368  586  446  172]
 [ 153  273 1088  206]
 [ 310   95   49 1303]]
n_estimators = 50 max_depth = [ 1.  0. 30.  1.  2.  1.  3.  4.  6.]
[[ 877  267  203  269]
 [ 368  586  446  172]
 [ 153  273 1088  206]
 [ 310   95   49 1303]]
n_estimators = 50 max_depth = [ 0.  1. 65.  1.  6.  1.  2.  2.  6.]
[[ 877  267  203  269]
 [ 368  586  446  172]
 [ 153  273 1088  206]
 [ 310   95   49 1303]]
n_estimators = 50 max_depth = [ 0.

D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


n_estimators = 50 max_depth = [ 0.  1. 38.  0.  3.  4.  3.  1.  6.]
[[ 932  268  170  246]
 [ 300  721  377  174]
 [ 145  257 1130  188]
 [ 268   83   44 1362]]
n_estimators = 50 max_depth = [ 1.  1. 48.  1.  1.  0.  2.  2.  6.]
[[ 932  268  170  246]
 [ 300  721  377  174]
 [ 145  257 1130  188]
 [ 268   83   44 1362]]
n_estimators = 50 max_depth = [ 0.  1. 51.  1.  1.  3.  3.  4.  6.]
[[ 932  268  170  246]
 [ 300  721  377  174]
 [ 145  257 1130  188]
 [ 268   83   44 1362]]
n_estimators = 50 max_depth = [ 1.  1. 73.  1.  1.  1.  1.  2.  2.]
[[ 932  268  170  246]
 [ 300  721  377  174]
 [ 145  257 1130  188]
 [ 268   83   44 1362]]
n_estimators = 50 max_depth = [ 1.  0. 30.  1.  2.  1.  3.  4.  6.]
[[ 932  268  170  246]
 [ 300  721  377  174]
 [ 145  257 1130  188]
 [ 268   83   44 1362]]
n_estimators = 50 max_depth = [ 0.  1. 65.  1.  6.  1.  2.  2.  6.]
[[ 932  268  170  246]
 [ 300  721  377  174]
 [ 145  257 1130  188]
 [ 268   83   44 1362]]
n_estimators = 50 max_depth = [ 0.

D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


n_estimators = 50 max_depth = [ 0.  1. 38.  0.  3.  4.  3.  1.  6.]
[[1067  209  154  186]
 [ 242  855  332  143]
 [ 125  218 1231  146]
 [ 203   56   41 1457]]
n_estimators = 50 max_depth = [ 1.  1. 48.  1.  1.  0.  2.  2.  6.]
[[1067  209  154  186]
 [ 242  855  332  143]
 [ 125  218 1231  146]
 [ 203   56   41 1457]]
n_estimators = 50 max_depth = [ 0.  1. 51.  1.  1.  3.  3.  4.  6.]
[[1067  209  154  186]
 [ 242  855  332  143]
 [ 125  218 1231  146]
 [ 203   56   41 1457]]
n_estimators = 50 max_depth = [ 1.  1. 73.  1.  1.  1.  1.  2.  2.]
[[1067  209  154  186]
 [ 242  855  332  143]
 [ 125  218 1231  146]
 [ 203   56   41 1457]]
n_estimators = 50 max_depth = [ 1.  0. 30.  1.  2.  1.  3.  4.  6.]
[[1067  209  154  186]
 [ 242  855  332  143]
 [ 125  218 1231  146]
 [ 203   56   41 1457]]
n_estimators = 50 max_depth = [ 0.  1. 65.  1.  6.  1.  2.  2.  6.]
[[1067  209  154  186]
 [ 242  855  332  143]
 [ 125  218 1231  146]
 [ 203   56   41 1457]]
n_estimators = 50 max_depth = [ 0.

D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


n_estimators = 50 max_depth = [ 0.  1. 38.  0.  3.  4.  3.  1.  6.]
[[1174  171  141  130]
 [ 166 1034  279   93]
 [  93  168 1344  115]
 [ 145   50   36 1526]]
n_estimators = 50 max_depth = [ 1.  1. 48.  1.  1.  0.  2.  2.  6.]
[[1174  171  141  130]
 [ 166 1034  279   93]
 [  93  168 1344  115]
 [ 145   50   36 1526]]
n_estimators = 50 max_depth = [ 0.  1. 51.  1.  1.  3.  3.  4.  6.]
[[1174  171  141  130]
 [ 166 1034  279   93]
 [  93  168 1344  115]
 [ 145   50   36 1526]]
n_estimators = 50 max_depth = [ 1.  1. 73.  1.  1.  1.  1.  2.  2.]
[[1174  171  141  130]
 [ 166 1034  279   93]
 [  93  168 1344  115]
 [ 145   50   36 1526]]
n_estimators = 50 max_depth = [ 1.  0. 30.  1.  2.  1.  3.  4.  6.]
[[1174  171  141  130]
 [ 166 1034  279   93]
 [  93  168 1344  115]
 [ 145   50   36 1526]]
n_estimators = 50 max_depth = [ 0.  1. 65.  1.  6.  1.  2.  2.  6.]
[[1174  171  141  130]
 [ 166 1034  279   93]
 [  93  168 1344  115]
 [ 145   50   36 1526]]
n_estimators = 50 max_depth = [ 0.

D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


n_estimators = 50 max_depth = [ 0.  1. 38.  0.  3.  4.  3.  1.  6.]
[[1334  124   99   59]
 [ 113 1171  226   62]
 [  64  119 1471   66]
 [  76   33   27 1621]]
n_estimators = 50 max_depth = [ 1.  1. 48.  1.  1.  0.  2.  2.  6.]
[[1334  124   99   59]
 [ 113 1171  226   62]
 [  64  119 1471   66]
 [  76   33   27 1621]]
n_estimators = 50 max_depth = [ 0.  1. 51.  1.  1.  3.  3.  4.  6.]
[[1334  124   99   59]
 [ 113 1171  226   62]
 [  64  119 1471   66]
 [  76   33   27 1621]]
n_estimators = 50 max_depth = [ 1.  1. 73.  1.  1.  1.  1.  2.  2.]
[[1334  124   99   59]
 [ 113 1171  226   62]
 [  64  119 1471   66]
 [  76   33   27 1621]]
n_estimators = 50 max_depth = [ 1.  0. 30.  1.  2.  1.  3.  4.  6.]
[[1334  124   99   59]
 [ 113 1171  226   62]
 [  64  119 1471   66]
 [  76   33   27 1621]]
n_estimators = 50 max_depth = [ 0.  1. 65.  1.  6.  1.  2.  2.  6.]
[[1334  124   99   59]
 [ 113 1171  226   62]
 [  64  119 1471   66]
 [  76   33   27 1621]]
n_estimators = 50 max_depth = [ 0.

D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


n_estimators = 50 max_depth = [ 0.  1. 38.  0.  3.  4.  3.  1.  6.]
[[1436   91   60   29]
 [  67 1305  166   34]
 [  30   88 1564   38]
 [  33   15   20 1689]]
n_estimators = 50 max_depth = [ 1.  1. 48.  1.  1.  0.  2.  2.  6.]
[[1436   91   60   29]
 [  67 1305  166   34]
 [  30   88 1564   38]
 [  33   15   20 1689]]
n_estimators = 50 max_depth = [ 0.  1. 51.  1.  1.  3.  3.  4.  6.]
[[1436   91   60   29]
 [  67 1305  166   34]
 [  30   88 1564   38]
 [  33   15   20 1689]]
n_estimators = 50 max_depth = [ 1.  1. 73.  1.  1.  1.  1.  2.  2.]
[[1436   91   60   29]
 [  67 1305  166   34]
 [  30   88 1564   38]
 [  33   15   20 1689]]
n_estimators = 50 max_depth = [ 1.  0. 30.  1.  2.  1.  3.  4.  6.]
[[1436   91   60   29]
 [  67 1305  166   34]
 [  30   88 1564   38]
 [  33   15   20 1689]]
n_estimators = 50 max_depth = [ 0.  1. 65.  1.  6.  1.  2.  2.  6.]
[[1436   91   60   29]
 [  67 1305  166   34]
 [  30   88 1564   38]
 [  33   15   20 1689]]
n_estimators = 50 max_depth = [ 0.

D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


n_estimators = 50 max_depth = [ 0.  1. 38.  0.  3.  4.  3.  1.  6.]
[[1512   50   41   13]
 [  54 1382  119   17]
 [  20   57 1615   28]
 [  18   11   12 1716]]
n_estimators = 50 max_depth = [ 1.  1. 48.  1.  1.  0.  2.  2.  6.]
[[1512   50   41   13]
 [  54 1382  119   17]
 [  20   57 1615   28]
 [  18   11   12 1716]]
n_estimators = 50 max_depth = [ 0.  1. 51.  1.  1.  3.  3.  4.  6.]
[[1512   50   41   13]
 [  54 1382  119   17]
 [  20   57 1615   28]
 [  18   11   12 1716]]
n_estimators = 50 max_depth = [ 1.  1. 73.  1.  1.  1.  1.  2.  2.]
[[1512   50   41   13]
 [  54 1382  119   17]
 [  20   57 1615   28]
 [  18   11   12 1716]]
n_estimators = 50 max_depth = [ 1.  0. 30.  1.  2.  1.  3.  4.  6.]
[[1512   50   41   13]
 [  54 1382  119   17]
 [  20   57 1615   28]
 [  18   11   12 1716]]
n_estimators = 50 max_depth = [ 0.  1. 65.  1.  6.  1.  2.  2.  6.]
[[1512   50   41   13]
 [  54 1382  119   17]
 [  20   57 1615   28]
 [  18   11   12 1716]]
n_estimators = 50 max_depth = [ 0.

D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


n_estimators = 50 max_depth = [ 0.  1. 38.  0.  3.  4.  3.  1.  6.]
[[1520   51   32   13]
 [  29 1447   85   11]
 [  10   48 1640   22]
 [  11    7   16 1723]]
n_estimators = 50 max_depth = [ 1.  1. 48.  1.  1.  0.  2.  2.  6.]
[[1520   51   32   13]
 [  29 1447   85   11]
 [  10   48 1640   22]
 [  11    7   16 1723]]
n_estimators = 50 max_depth = [ 0.  1. 51.  1.  1.  3.  3.  4.  6.]
[[1520   51   32   13]
 [  29 1447   85   11]
 [  10   48 1640   22]
 [  11    7   16 1723]]
n_estimators = 50 max_depth = [ 1.  1. 73.  1.  1.  1.  1.  2.  2.]
[[1520   51   32   13]
 [  29 1447   85   11]
 [  10   48 1640   22]
 [  11    7   16 1723]]
n_estimators = 50 max_depth = [ 1.  0. 30.  1.  2.  1.  3.  4.  6.]
[[1520   51   32   13]
 [  29 1447   85   11]
 [  10   48 1640   22]
 [  11    7   16 1723]]
n_estimators = 50 max_depth = [ 0.  1. 65.  1.  6.  1.  2.  2.  6.]
[[1520   51   32   13]
 [  29 1447   85   11]
 [  10   48 1640   22]
 [  11    7   16 1723]]
n_estimators = 50 max_depth = [ 0.

D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


n_estimators = 50 max_depth = [ 0.  1. 38.  0.  3.  4.  3.  1.  6.]
[[1534   44   27   11]
 [  37 1455   69   11]
 [  14   50 1635   21]
 [  12    7   15 1723]]
n_estimators = 50 max_depth = [ 1.  1. 48.  1.  1.  0.  2.  2.  6.]
[[1534   44   27   11]
 [  37 1455   69   11]
 [  14   50 1635   21]
 [  12    7   15 1723]]
n_estimators = 50 max_depth = [ 0.  1. 51.  1.  1.  3.  3.  4.  6.]
[[1534   44   27   11]
 [  37 1455   69   11]
 [  14   50 1635   21]
 [  12    7   15 1723]]
n_estimators = 50 max_depth = [ 1.  1. 73.  1.  1.  1.  1.  2.  2.]
[[1534   44   27   11]
 [  37 1455   69   11]
 [  14   50 1635   21]
 [  12    7   15 1723]]
n_estimators = 50 max_depth = [ 1.  0. 30.  1.  2.  1.  3.  4.  6.]
[[1534   44   27   11]
 [  37 1455   69   11]
 [  14   50 1635   21]
 [  12    7   15 1723]]
n_estimators = 50 max_depth = [ 0.  1. 65.  1.  6.  1.  2.  2.  6.]
[[1534   44   27   11]
 [  37 1455   69   11]
 [  14   50 1635   21]
 [  12    7   15 1723]]
n_estimators = 50 max_depth = [ 0.

D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


n_estimators = 50 max_depth = [ 0.  1. 38.  0.  3.  4.  3.  1.  6.]
[[1534   46   26   10]
 [  33 1457   74    8]
 [  14   43 1644   19]
 [  13    7   17 1720]]
n_estimators = 50 max_depth = [ 1.  1. 48.  1.  1.  0.  2.  2.  6.]
[[1534   46   26   10]
 [  33 1457   74    8]
 [  14   43 1644   19]
 [  13    7   17 1720]]
n_estimators = 50 max_depth = [ 0.  1. 51.  1.  1.  3.  3.  4.  6.]
[[1534   46   26   10]
 [  33 1457   74    8]
 [  14   43 1644   19]
 [  13    7   17 1720]]
n_estimators = 50 max_depth = [ 1.  1. 73.  1.  1.  1.  1.  2.  2.]
[[1534   46   26   10]
 [  33 1457   74    8]
 [  14   43 1644   19]
 [  13    7   17 1720]]
n_estimators = 50 max_depth = [ 1.  0. 30.  1.  2.  1.  3.  4.  6.]
[[1534   46   26   10]
 [  33 1457   74    8]
 [  14   43 1644   19]
 [  13    7   17 1720]]
n_estimators = 50 max_depth = [ 0.  1. 65.  1.  6.  1.  2.  2.  6.]
[[1534   46   26   10]
 [  33 1457   74    8]
 [  14   43 1644   19]
 [  13    7   17 1720]]
n_estimators = 50 max_depth = [ 0.

D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


n_estimators = 50 max_depth = [ 0.  1. 38.  0.  3.  4.  3.  1.  6.]
[[1526   52   26   12]
 [  26 1466   69   11]
 [  12   48 1637   23]
 [  11    7   12 1727]]
n_estimators = 50 max_depth = [ 1.  1. 48.  1.  1.  0.  2.  2.  6.]
[[1526   52   26   12]
 [  26 1466   69   11]
 [  12   48 1637   23]
 [  11    7   12 1727]]
n_estimators = 50 max_depth = [ 0.  1. 51.  1.  1.  3.  3.  4.  6.]
[[1526   52   26   12]
 [  26 1466   69   11]
 [  12   48 1637   23]
 [  11    7   12 1727]]
n_estimators = 50 max_depth = [ 1.  1. 73.  1.  1.  1.  1.  2.  2.]
[[1526   52   26   12]
 [  26 1466   69   11]
 [  12   48 1637   23]
 [  11    7   12 1727]]
n_estimators = 50 max_depth = [ 1.  0. 30.  1.  2.  1.  3.  4.  6.]
[[1526   52   26   12]
 [  26 1466   69   11]
 [  12   48 1637   23]
 [  11    7   12 1727]]
n_estimators = 50 max_depth = [ 0.  1. 65.  1.  6.  1.  2.  2.  6.]
[[1526   52   26   12]
 [  26 1466   69   11]
 [  12   48 1637   23]
 [  11    7   12 1727]]
n_estimators = 50 max_depth = [ 0.

D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


KeyboardInterrupt: 

In [35]:
YY[1000:1020]

array([2., 3., 2., 3., 3., 2., 2., 2., 2., 3., 4., 1., 3., 2., 3., 1., 1.,
       4., 4., 3.])

In [36]:
x_new = XX[1000:1020]
lst_1 = list(range(1,20))
lst_3 = list(range(50,200))

#k = []
for i in lst_3:
 for j in lst_1:
  model=RandomForestClassifier(max_depth = 9, min_samples_leaf = 2, min_samples_split = 2, n_estimators= 90)
  model.fit(X,Y)
  res = model.predict(x_new)
  print(f'n_estimators:{i} глубина: {j} предсказание: {res}')
#  k.append(res)

n_estimators:50 глубина: 1 предсказание: [1. 3. 3. 3. 4. 3. 2. 4. 2. 1. 4. 4. 3. 1. 4. 4. 3. 4. 4. 2.]
n_estimators:50 глубина: 2 предсказание: [1. 3. 3. 3. 4. 3. 2. 2. 2. 3. 4. 4. 3. 1. 4. 4. 3. 4. 4. 2.]
n_estimators:50 глубина: 3 предсказание: [1. 3. 3. 3. 4. 3. 1. 2. 2. 3. 4. 4. 3. 1. 4. 4. 3. 4. 4. 2.]
n_estimators:50 глубина: 4 предсказание: [1. 3. 2. 3. 4. 3. 2. 2. 2. 3. 4. 4. 3. 1. 4. 4. 3. 4. 4. 3.]
n_estimators:50 глубина: 5 предсказание: [1. 3. 3. 3. 4. 3. 2. 4. 2. 1. 4. 4. 3. 1. 4. 4. 3. 4. 4. 2.]
n_estimators:50 глубина: 6 предсказание: [1. 3. 3. 3. 4. 3. 2. 4. 2. 3. 4. 4. 3. 1. 4. 4. 3. 4. 4. 2.]
n_estimators:50 глубина: 7 предсказание: [1. 3. 3. 3. 4. 3. 2. 4. 2. 1. 4. 4. 3. 1. 4. 4. 3. 4. 4. 2.]
n_estimators:50 глубина: 8 предсказание: [1. 3. 3. 3. 4. 3. 1. 4. 2. 3. 4. 4. 3. 1. 4. 4. 3. 4. 4. 2.]
n_estimators:50 глубина: 9 предсказание: [1. 3. 3. 3. 4. 3. 2. 2. 2. 1. 4. 4. 3. 1. 4. 4. 3. 4. 4. 2.]
n_estimators:50 глубина: 10 предсказание: [1. 3. 3. 3. 4. 3. 2. 4. 2. 3. 

KeyboardInterrupt: 

In [32]:
kfold=KFold(n_splits=3,random_state=7,shuffle=True)

model=XGBClassifier(seed = 7, n_estimators = 50, max_depth = 12, learning_rate = 0.3,eval_metric='mlogloss')

results=cross_val_score(model, X, Y, cv=kfold)

model.fit(X,Y)

results.mean(),results.std()

D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
D:\Programs\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is depre

KeyboardInterrupt: 

In [ ]:
=============================================================================================================

In [1]:
import pandas as pd
import numpy as np
from pandas import read_csv

In [2]:
df=read_csv('D:\Политех\Класиффикация\Сегментация_клиентов\Train_cleared_!!!!!!!!.csv')

In [3]:
df=df.filter(regex='^(?!.*Unnamed).*$')

In [4]:
df_T=read_csv('D:\Политех\Класиффикация\Сегментация_клиентов\Test_cleared_!!!!!!!!.csv')

In [5]:
df_T=df_T.filter(regex='^(?!.*Unnamed).*$')

**Обучающий_набор**

In [6]:
array = df.values
array
X = array[:,0:9]
Y = array[:,9]

**Тестовый_набор**

In [7]:
array_T = df_T.values
array_T
XX = array_T[:,0:9]
YY = array_T[:,9]

In [8]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
# отбор признаков:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
# ансамблевые функции:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
import numpy as np
from sklearn.linear_model import RidgeClassifier
from sklearn.model_selection import GridSearchCV
from scipy.stats import uniform
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import train_test_split
# сохраняет параметры после перезагрузки:
import pickle
import joblib

In [ ]:
========================================================================================================================

# **GrideSearchCV**

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor

In [11]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, shuffle=True, random_state=7) 

In [12]:
clf = RandomForestClassifier()

In [13]:
params = {'n_estimators': range (10, 250, 10),
          'max_depth': range (1,13, 2),
          'min_samples_leaf': range (1,8),
          'min_samples_split': range (2,10,2) }

In [14]:
grid = GridSearchCV(clf, param_grid = params, cv=3,verbose=1,n_jobs=-1)

In [15]:
grid.fit(X_train,Y_train)

Fitting 3 folds for each of 4032 candidates, totalling 12096 fits


GridSearchCV(cv=3, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_depth': range(1, 13, 2),
                         'min_samples_leaf': range(1, 8),
                         'min_samples_split': range(2, 10, 2),
                         'n_estimators': range(10, 250, 10)},
             verbose=1)

In [16]:
print(grid.best_params_)
print(grid.best_estimator_)

{'max_depth': 7, 'min_samples_leaf': 3, 'min_samples_split': 2, 'n_estimators': 60}
RandomForestClassifier(max_depth=7, min_samples_leaf=3, n_estimators=60)


In [17]:
from sklearn.metrics import classification_report, confusion_matrix

In [18]:
grid_predictions = grid.predict(X_test)
print(classification_report(Y_test, grid_predictions))

              precision    recall  f1-score   support

         1.0       0.46      0.48      0.47       351
         2.0       0.40      0.34      0.37       347
         3.0       0.56      0.53      0.55       361
         4.0       0.59      0.68      0.63       373

    accuracy                           0.51      1432
   macro avg       0.50      0.51      0.50      1432
weighted avg       0.51      0.51      0.51      1432



In [19]:
print(confusion_matrix(Y_test, grid_predictions))

[[169  73  39  70]
 [ 78 119 103  47]
 [ 32  78 192  59]
 [ 85  29   7 252]]


In [ ]:
================================================================================================================

In [20]:
model = RandomForestClassifier(max_depth=7, min_samples_leaf=3, n_estimators=60)

In [21]:
model.fit(X_train,Y_train)

RandomForestClassifier(max_depth=7, min_samples_leaf=3, n_estimators=60)

In [22]:
new_predictions = model.predict(X_test)

In [23]:
print(classification_report(Y_test, new_predictions))
print(confusion_matrix(Y_test, new_predictions))

              precision    recall  f1-score   support

         1.0       0.48      0.46      0.47       351
         2.0       0.41      0.37      0.39       347
         3.0       0.58      0.53      0.56       361
         4.0       0.58      0.69      0.63       373

    accuracy                           0.52      1432
   macro avg       0.51      0.52      0.51      1432
weighted avg       0.52      0.52      0.52      1432

[[163  72  39  77]
 [ 75 130  93  49]
 [ 27  83 193  58]
 [ 77  31   7 258]]


In [ ]:
================================================================================================================

In [24]:
kfold=KFold(n_splits=3,random_state=7,shuffle=True)
results=cross_val_score(model, X, Y, cv=3)
results.mean()

0.5112624410686224