In [8]:
import pandas as pd
import numpy as np
from pandas import read_csv

In [9]:
df=read_csv('D:\Политех\Класиффикация\Сегментация_клиентов\Train_cleared_dropna.csv')

In [10]:
df_T=read_csv('D:\Политех\Класиффикация\Сегментация_клиентов\TEST_cleared_dropna.csv')

In [11]:
df=df.filter(regex='^(?!.*Unnamed).*$')

In [12]:
df_T=df_T.filter(regex='^(?!.*Unnamed).*$')

================================================================

**Обучающий_набор**

In [13]:
array = df.values
array

array([[ 1.,  0., 22., ...,  4.,  4.,  4.],
       [ 0.,  1., 67., ...,  1.,  6.,  2.],
       [ 1.,  1., 67., ...,  2.,  6.,  2.],
       ...,
       [ 0.,  0., 33., ...,  1.,  6.,  4.],
       [ 0.,  0., 27., ...,  4.,  6.,  2.],
       [ 1.,  1., 37., ...,  3.,  4.,  2.]])

In [14]:
X = array[:,0:9]
Y = array[:,9]

In [15]:
X

array([[ 1.,  0., 22., ...,  3.,  4.,  4.],
       [ 0.,  1., 67., ...,  3.,  1.,  6.],
       [ 1.,  1., 67., ...,  1.,  2.,  6.],
       ...,
       [ 0.,  0., 33., ...,  3.,  1.,  6.],
       [ 0.,  0., 27., ...,  3.,  4.,  6.],
       [ 1.,  1., 37., ...,  2.,  3.,  4.]])

In [16]:
Y

array([4., 2., 2., ..., 4., 2., 2.])

==============================================================

**Тестовый_набор**

In [17]:
array_T = df.values
array_T

array([[ 1.,  0., 22., ...,  4.,  4.,  4.],
       [ 0.,  1., 67., ...,  1.,  6.,  2.],
       [ 1.,  1., 67., ...,  2.,  6.,  2.],
       ...,
       [ 0.,  0., 33., ...,  1.,  6.,  4.],
       [ 0.,  0., 27., ...,  4.,  6.,  2.],
       [ 1.,  1., 37., ...,  3.,  4.,  2.]])

In [18]:
XX = array_T[:,0:9]
YY = array_T[:,9]

In [19]:
XX

array([[ 1.,  0., 22., ...,  3.,  4.,  4.],
       [ 0.,  1., 67., ...,  3.,  1.,  6.],
       [ 1.,  1., 67., ...,  1.,  2.,  6.],
       ...,
       [ 0.,  0., 33., ...,  3.,  1.,  6.],
       [ 0.,  0., 27., ...,  3.,  4.,  6.],
       [ 1.,  1., 37., ...,  2.,  3.,  4.]])

In [20]:
YY

array([4., 2., 2., ..., 4., 2., 2.])

=====================================================

In [5]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
# отбор признаков:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
# ансамблевые функции:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
import numpy as np
from sklearn.linear_model import RidgeClassifier
from sklearn.model_selection import GridSearchCV
from scipy.stats import uniform
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import train_test_split
# сохраняет параметры после перезагрузки:
import pickle
import joblib

In [ ]:
+++++++++++++++++++++++++++++++++++++++++++++++++++++

In [34]:
lst_1 = list(range(6,10))
lst_2 = list(range(2,9))
lst_3 = list(range(100,200))
k = []

In [35]:
for s in lst_3:
 model=AdaBoostClassifier(n_estimators = s, random_state = 7)
 for i in lst_2:
   kfold=KFold(n_splits=i,random_state=7,shuffle=True)
   for j in lst_1:
      test=SelectKBest(score_func=f_classif, k=j)
      fit=test.fit(X,Y)
      features=fit.transform(X)
      results=cross_val_score(model, features, Y, cv=kfold)
      res = results.mean()
      k.append(res)
      print(f'n_splits: {i} KBest: {j} {res}')
   print(f'n_estimators = {s} n_splits = {i} max = {max(k)}')

n_splits: 2 KBest: 6 0.5032254575997815
n_splits: 2 KBest: 7 0.5084765229224003
n_splits: 2 KBest: 8 0.510577093123478
n_splits: 2 KBest: 9 0.5057763429404165
n_estimators = 100 n_splits = 2 max = 0.510577093123478
n_splits: 3 KBest: 6 0.5147783351050098
n_splits: 3 KBest: 7 0.5108767292758092
n_splits: 3 KBest: 8 0.5168784775821121
n_splits: 3 KBest: 9 0.5176290929408114
n_estimators = 100 n_splits = 3 max = 0.5176290929408114
n_splits: 4 KBest: 6 0.5074281062154916
n_splits: 4 KBest: 7 0.5105797267917365
n_splits: 4 KBest: 8 0.5141801771698482
n_splits: 4 KBest: 9 0.5099791266236549
n_estimators = 100 n_splits = 4 max = 0.5176290929408114
n_splits: 5 KBest: 6 0.5135783945986496
n_splits: 5 KBest: 7 0.5090772693173293
n_splits: 5 KBest: 8 0.5149287321830458
n_splits: 5 KBest: 9 0.5101275318829709
n_estimators = 100 n_splits = 5 max = 0.5176290929408114
n_splits: 6 KBest: 6 0.5129756218865128
n_splits: 6 KBest: 7 0.5128268232228628
n_splits: 6 KBest: 8 0.5162775737033163
n_splits: 6 KB

KeyboardInterrupt: 

In [ ]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
x_new = XX[1000:1020]
for s in lst_3:
 model=AdaBoostClassifier(n_estimators = s, random_state = 7)
 model.fit(X,Y)
 for j in x_new:
      predictions = model.predict(XX)
      print(confusion_matrix(YY, predictions))


In [ ]:
predictions = model.predict(XX)
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
print(confusion_matrix(YY, predictions))

In [40]:
YY[1000:1020]

array([2., 3., 2., 3., 3., 2., 2., 2., 2., 3., 4., 1., 3., 2., 3., 1., 1.,
       4., 4., 3.])

In [49]:
x_new = XX[1000:1020]
lst_3 = list(range(1,200))
k = []
for i in lst_3:
  model=AdaBoostClassifier(n_estimators = i, random_state = 7)
  model.fit(X,Y)
  res = model.predict(x_new)
  print(f'n_estimators:{i} предсказание: {res}')
  k.append(res)

n_estimators:1 предсказание: [3. 3. 3. 3. 4. 3. 3. 4. 3. 4. 4. 4. 3. 4. 4. 4. 3. 4. 4. 3.]
n_estimators:2 предсказание: [1. 3. 3. 3. 4. 1. 3. 4. 1. 4. 4. 4. 3. 1. 4. 4. 3. 4. 4. 1.]
n_estimators:3 предсказание: [1. 3. 3. 3. 4. 3. 1. 4. 3. 4. 4. 4. 3. 4. 4. 4. 3. 4. 4. 3.]
n_estimators:4 предсказание: [1. 3. 3. 3. 4. 3. 1. 4. 3. 4. 4. 4. 3. 4. 4. 4. 3. 4. 4. 3.]
n_estimators:5 предсказание: [4. 3. 3. 3. 4. 3. 1. 4. 3. 4. 4. 4. 3. 4. 4. 4. 3. 4. 4. 2.]
n_estimators:6 предсказание: [4. 3. 3. 3. 4. 3. 1. 4. 3. 4. 4. 4. 3. 1. 4. 4. 3. 4. 4. 2.]
n_estimators:7 предсказание: [4. 3. 3. 3. 4. 3. 1. 4. 2. 4. 4. 4. 3. 1. 4. 4. 3. 4. 4. 2.]
n_estimators:8 предсказание: [1. 3. 3. 3. 4. 3. 1. 4. 2. 4. 4. 4. 3. 4. 4. 4. 3. 4. 4. 2.]
n_estimators:9 предсказание: [1. 3. 3. 3. 4. 3. 1. 4. 2. 1. 4. 4. 3. 4. 4. 4. 3. 4. 4. 2.]
n_estimators:10 предсказание: [1. 3. 3. 3. 4. 2. 1. 4. 2. 1. 4. 4. 3. 1. 4. 4. 3. 4. 4. 2.]
n_estimators:11 предсказание: [1. 3. 3. 3. 4. 3. 1. 4. 2. 1. 4. 4. 3. 1. 4. 4. 3. 4. 4. 2

n_estimators:91 предсказание: [1. 3. 3. 3. 4. 3. 1. 4. 2. 1. 4. 1. 3. 1. 1. 1. 3. 4. 4. 3.]
n_estimators:92 предсказание: [1. 3. 3. 3. 4. 3. 1. 4. 2. 1. 4. 1. 3. 1. 1. 4. 3. 4. 4. 3.]
n_estimators:93 предсказание: [1. 3. 3. 3. 4. 3. 1. 4. 2. 1. 4. 1. 3. 1. 1. 1. 3. 4. 4. 3.]
n_estimators:94 предсказание: [1. 3. 3. 3. 4. 3. 1. 4. 2. 1. 4. 1. 3. 1. 1. 4. 3. 4. 4. 3.]
n_estimators:95 предсказание: [1. 3. 3. 3. 4. 3. 1. 4. 2. 1. 4. 1. 3. 1. 1. 4. 3. 4. 4. 3.]


KeyboardInterrupt: 

In [ ]:
=============================================================================================================

In [1]:
import pandas as pd
import numpy as np
from pandas import read_csv

In [2]:
df=read_csv('D:\Политех\Класиффикация\Сегментация_клиентов\Train_cleared_!!!!!!!!.csv')

In [3]:
df=df.filter(regex='^(?!.*Unnamed).*$')

In [4]:
df_T=read_csv('D:\Политех\Класиффикация\Сегментация_клиентов\Test_cleared_!!!!!!!!.csv')

In [5]:
df_T=df_T.filter(regex='^(?!.*Unnamed).*$')

**Обучающий_набор**

In [6]:
array = df.values
array
X = array[:,0:9]
Y = array[:,9]

**Тестовый_набор**

In [7]:
array_T = df_T.values
array_T
XX = array_T[:,0:9]
YY = array_T[:,9]

In [8]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
# отбор признаков:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
# ансамблевые функции:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
import numpy as np
from sklearn.linear_model import RidgeClassifier
from sklearn.model_selection import GridSearchCV
from scipy.stats import uniform
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import train_test_split
# сохраняет параметры после перезагрузки:
import pickle
import joblib

In [ ]:
========================================================================================================================

# **GrideSearchCV**

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsClassifier

In [10]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, shuffle=True, random_state=7) 

In [11]:
clf = AdaBoostClassifier()

In [128]:
params = {'n_estimators':range(10,200,25),'learning_rate':np.linspace(0,1,10)}

In [129]:
grid = GridSearchCV(clf, param_grid = params, cv=3,verbose=1,n_jobs=-1)

In [130]:
grid.fit(X_train,Y_train)

Fitting 3 folds for each of 80 candidates, totalling 240 fits


D:\Programs\lib\site-packages\sklearn\model_selection\_search.py:922: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
        nan        nan 0.46821951 0.48335214 0.48404639 0.47845883
 0.47776294 0.47962677 0.47753082 0.48195468 0.47962628 0.47799344
 0.48102309 0.48381671 0.48032444 0.47962547 0.48079031 0.47659858
 0.48381704 0.47776294 0.48055721 0.48055803 0.47822833 0.47869388
 0.47450247 0.47706364 0.47264255 0.4789273  0.4793922  0.47939285
 0.47613401 0.47566716 0.47450328 0.4738048  0.48358345 0.48079162
 0.47822687 0.47659874 0.47915845 0.47450215 0.47217505 0.46844935
 0.47589961 0.47916105 0.47590156 0.48009134 0.47566765 0.47427051
 0.47427083 0.4735717  0.47869437 0.47706641 0.48125473 0.47659858
 0.48009118 0.47846013 0.47566781 0.47729625 0.47915829 0.48032379
 0.47497062 0.47357202 0.47753017 0.47543389 0.47403757 0.4733386
 0.47496607 0.47310582 0.47636662 0.47240994 0.47124509 0.47496981


GridSearchCV(cv=3, estimator=AdaBoostClassifier(), n_jobs=-1,
             param_grid={'learning_rate': array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
                         'n_estimators': range(10, 200, 25)},
             verbose=1)

In [131]:
print(grid.best_params_)
print(grid.best_estimator_)

{'learning_rate': 0.1111111111111111, 'n_estimators': 60}
AdaBoostClassifier(learning_rate=0.1111111111111111, n_estimators=60)


In [132]:
from sklearn.metrics import classification_report, confusion_matrix

In [133]:
grid_predictions = grid.predict(X_test)
print(classification_report(Y_test, grid_predictions))

              precision    recall  f1-score   support

         1.0       0.45      0.49      0.47       351
         2.0       0.42      0.25      0.32       347
         3.0       0.50      0.61      0.55       361
         4.0       0.60      0.64      0.62       373

    accuracy                           0.50      1432
   macro avg       0.49      0.50      0.49      1432
weighted avg       0.49      0.50      0.49      1432



In [134]:
print(confusion_matrix(Y_test, grid_predictions))

[[171  51  67  62]
 [ 78  88 139  42]
 [ 38  48 220  55]
 [ 97  23  14 239]]


In [ ]:
================================================================================================================

In [140]:
model = AdaBoostClassifier()

In [141]:
model.fit(X_train,Y_train)

AdaBoostClassifier()

In [142]:
new_predictions = model.predict(X_test)

In [143]:
print(classification_report(Y_test, new_predictions))
print(confusion_matrix(Y_test, new_predictions))

              precision    recall  f1-score   support

         1.0       0.42      0.44      0.43       351
         2.0       0.40      0.36      0.38       347
         3.0       0.49      0.49      0.49       361
         4.0       0.61      0.64      0.62       373

    accuracy                           0.48      1432
   macro avg       0.48      0.48      0.48      1432
weighted avg       0.48      0.48      0.48      1432

[[153  80  58  60]
 [ 79 125 106  37]
 [ 46  81 178  56]
 [ 90  24  22 237]]


In [ ]:
================================================================================================================

In [144]:
kfold=KFold(n_splits=3,random_state=7,shuffle=True)
results=cross_val_score(model, X, Y, cv=3)
results.mean()

0.4857691636109656