In [1]:
import pandas as pd
import numpy as np
from pandas import read_csv

In [2]:
df=read_csv('D:\Политех\Класиффикация\Сегментация_клиентов\Train_cleared_dropna.csv')

In [3]:
df_T=read_csv('D:\Политех\Класиффикация\Сегментация_клиентов\TEST_cleared_dropna.csv')

In [4]:
df=df.filter(regex='^(?!.*Unnamed).*$')

In [5]:
df_T=df_T.filter(regex='^(?!.*Unnamed).*$')

================================================================

**Обучающий_набор**

In [6]:
array = df.values
array

array([[ 1.,  0., 22., ...,  4.,  4.,  4.],
       [ 0.,  1., 67., ...,  1.,  6.,  2.],
       [ 1.,  1., 67., ...,  2.,  6.,  2.],
       ...,
       [ 0.,  0., 33., ...,  1.,  6.,  4.],
       [ 0.,  0., 27., ...,  4.,  6.,  2.],
       [ 1.,  1., 37., ...,  3.,  4.,  2.]])

In [7]:
X = array[:,0:9]
Y = array[:,9]

In [8]:
X

array([[ 1.,  0., 22., ...,  3.,  4.,  4.],
       [ 0.,  1., 67., ...,  3.,  1.,  6.],
       [ 1.,  1., 67., ...,  1.,  2.,  6.],
       ...,
       [ 0.,  0., 33., ...,  3.,  1.,  6.],
       [ 0.,  0., 27., ...,  3.,  4.,  6.],
       [ 1.,  1., 37., ...,  2.,  3.,  4.]])

In [9]:
Y

array([4., 2., 2., ..., 4., 2., 2.])

==============================================================

**Тестовый_набор**

In [10]:
array_T = df.values
array_T

array([[ 1.,  0., 22., ...,  4.,  4.,  4.],
       [ 0.,  1., 67., ...,  1.,  6.,  2.],
       [ 1.,  1., 67., ...,  2.,  6.,  2.],
       ...,
       [ 0.,  0., 33., ...,  1.,  6.,  4.],
       [ 0.,  0., 27., ...,  4.,  6.,  2.],
       [ 1.,  1., 37., ...,  3.,  4.,  2.]])

In [11]:
XX = array_T[:,0:9]
YY = array_T[:,9]

In [12]:
XX

array([[ 1.,  0., 22., ...,  3.,  4.,  4.],
       [ 0.,  1., 67., ...,  3.,  1.,  6.],
       [ 1.,  1., 67., ...,  1.,  2.,  6.],
       ...,
       [ 0.,  0., 33., ...,  3.,  1.,  6.],
       [ 0.,  0., 27., ...,  3.,  4.,  6.],
       [ 1.,  1., 37., ...,  2.,  3.,  4.]])

In [13]:
YY

array([4., 2., 2., ..., 4., 2., 2.])

=====================================================

In [17]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
# отбор признаков:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
# ансамблевые функции:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
import numpy as np
from sklearn.linear_model import RidgeClassifier
from sklearn.model_selection import GridSearchCV
from scipy.stats import uniform
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import train_test_split
# сохраняет параметры после перезагрузки:
import pickle
import joblib

In [18]:
+++++++++++++++++++++++++++++++++++++++++++++++++++++

SyntaxError: invalid syntax (Temp/ipykernel_17880/441078461.py, line 1)

In [22]:
lst_1 = list(range(6,10))
lst_2 = list(range(3,4))
lst_3 = list(range(100,200))
k = []

In [29]:
for s in lst_3:
 model = GradientBoostingClassifier(n_estimators = s, random_state = 7)
 for i in lst_2:
   kfold=KFold(n_splits=i,random_state=7,shuffle=True)
   for j in lst_1:
      test=SelectKBest(score_func=f_classif, k=j)
      fit=test.fit(X,Y)
      features=fit.transform(X)
      results=cross_val_score(model, features, Y, cv=kfold)
      res = results.mean()
      k.append(res)
      print(f'n_splits: {i} KBest: {j} {res}')
   print(f'n_estimators = {s} n_splits = {i} max = {max(k)}')

n_splits: 3 KBest: 6 0.5344321239868246
n_splits: 3 KBest: 7 0.5353330245226233


KeyboardInterrupt: 

In [30]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
x_new = XX[1000:1020]
for s in lst_3:
 model=GradientBoostingClassifier(n_estimators = s, random_state = 7)
 model.fit(X,Y)
 for j in x_new:
      predictions = model.predict(XX)
      print (f'n_estimators = {s}')
      print(confusion_matrix(YY, predictions))


n_estimators = 50
[[ 838  283  194  301]
 [ 365  559  466  182]
 [ 155  272 1071  222]
 [ 328   90   38 1301]]
n_estimators = 50
[[ 838  283  194  301]
 [ 365  559  466  182]
 [ 155  272 1071  222]
 [ 328   90   38 1301]]
n_estimators = 50
[[ 838  283  194  301]
 [ 365  559  466  182]
 [ 155  272 1071  222]
 [ 328   90   38 1301]]
n_estimators = 50
[[ 838  283  194  301]
 [ 365  559  466  182]
 [ 155  272 1071  222]
 [ 328   90   38 1301]]
n_estimators = 50
[[ 838  283  194  301]
 [ 365  559  466  182]
 [ 155  272 1071  222]
 [ 328   90   38 1301]]
n_estimators = 50
[[ 838  283  194  301]
 [ 365  559  466  182]
 [ 155  272 1071  222]
 [ 328   90   38 1301]]
n_estimators = 50
[[ 838  283  194  301]
 [ 365  559  466  182]
 [ 155  272 1071  222]
 [ 328   90   38 1301]]
n_estimators = 50
[[ 838  283  194  301]
 [ 365  559  466  182]
 [ 155  272 1071  222]
 [ 328   90   38 1301]]
n_estimators = 50
[[ 838  283  194  301]
 [ 365  559  466  182]
 [ 155  272 1071  222]
 [ 328   90   38 1301]]
n

[[ 839  280  197  300]
 [ 366  560  465  181]
 [ 159  272 1070  219]
 [ 329   87   40 1301]]
n_estimators = 53
[[ 839  280  197  300]
 [ 366  560  465  181]
 [ 159  272 1070  219]
 [ 329   87   40 1301]]
n_estimators = 54
[[ 840  282  196  298]
 [ 366  564  463  179]
 [ 158  273 1070  219]
 [ 329   86   40 1302]]
n_estimators = 54
[[ 840  282  196  298]
 [ 366  564  463  179]
 [ 158  273 1070  219]
 [ 329   86   40 1302]]
n_estimators = 54
[[ 840  282  196  298]
 [ 366  564  463  179]
 [ 158  273 1070  219]
 [ 329   86   40 1302]]
n_estimators = 54
[[ 840  282  196  298]
 [ 366  564  463  179]
 [ 158  273 1070  219]
 [ 329   86   40 1302]]
n_estimators = 54
[[ 840  282  196  298]
 [ 366  564  463  179]
 [ 158  273 1070  219]
 [ 329   86   40 1302]]
n_estimators = 54
[[ 840  282  196  298]
 [ 366  564  463  179]
 [ 158  273 1070  219]
 [ 329   86   40 1302]]
n_estimators = 54
[[ 840  282  196  298]
 [ 366  564  463  179]
 [ 158  273 1070  219]
 [ 329   86   40 1302]]
n_estimators = 54
[

[[ 840  282  197  297]
 [ 367  570  457  178]
 [ 159  274 1070  217]
 [ 331   87   41 1298]]
n_estimators = 57
[[ 840  282  197  297]
 [ 367  570  457  178]
 [ 159  274 1070  217]
 [ 331   87   41 1298]]
n_estimators = 57
[[ 840  282  197  297]
 [ 367  570  457  178]
 [ 159  274 1070  217]
 [ 331   87   41 1298]]
n_estimators = 57
[[ 840  282  197  297]
 [ 367  570  457  178]
 [ 159  274 1070  217]
 [ 331   87   41 1298]]
n_estimators = 58
[[ 836  284  198  298]
 [ 364  573  458  177]
 [ 156  275 1072  217]
 [ 326   88   41 1302]]
n_estimators = 58
[[ 836  284  198  298]
 [ 364  573  458  177]
 [ 156  275 1072  217]
 [ 326   88   41 1302]]
n_estimators = 58
[[ 836  284  198  298]
 [ 364  573  458  177]
 [ 156  275 1072  217]
 [ 326   88   41 1302]]
n_estimators = 58
[[ 836  284  198  298]
 [ 364  573  458  177]
 [ 156  275 1072  217]
 [ 326   88   41 1302]]
n_estimators = 58
[[ 836  284  198  298]
 [ 364  573  458  177]
 [ 156  275 1072  217]
 [ 326   88   41 1302]]
n_estimators = 58
[

[[ 839  285  196  296]
 [ 365  576  453  178]
 [ 154  279 1070  217]
 [ 326   88   40 1303]]
n_estimators = 61
[[ 839  285  196  296]
 [ 365  576  453  178]
 [ 154  279 1070  217]
 [ 326   88   40 1303]]
n_estimators = 61
[[ 839  285  196  296]
 [ 365  576  453  178]
 [ 154  279 1070  217]
 [ 326   88   40 1303]]
n_estimators = 61
[[ 839  285  196  296]
 [ 365  576  453  178]
 [ 154  279 1070  217]
 [ 326   88   40 1303]]
n_estimators = 61
[[ 839  285  196  296]
 [ 365  576  453  178]
 [ 154  279 1070  217]
 [ 326   88   40 1303]]
n_estimators = 61
[[ 839  285  196  296]
 [ 365  576  453  178]
 [ 154  279 1070  217]
 [ 326   88   40 1303]]
n_estimators = 61
[[ 839  285  196  296]
 [ 365  576  453  178]
 [ 154  279 1070  217]
 [ 326   88   40 1303]]
n_estimators = 61
[[ 839  285  196  296]
 [ 365  576  453  178]
 [ 154  279 1070  217]
 [ 326   88   40 1303]]
n_estimators = 61
[[ 839  285  196  296]
 [ 365  576  453  178]
 [ 154  279 1070  217]
 [ 326   88   40 1303]]
n_estimators = 61
[

[[ 846  277  200  293]
 [ 365  578  452  177]
 [ 154  272 1076  218]
 [ 327   89   39 1302]]
n_estimators = 65
[[ 846  277  200  293]
 [ 365  578  452  177]
 [ 154  272 1076  218]
 [ 327   89   39 1302]]
n_estimators = 65
[[ 846  277  200  293]
 [ 365  578  452  177]
 [ 154  272 1076  218]
 [ 327   89   39 1302]]
n_estimators = 65
[[ 846  277  200  293]
 [ 365  578  452  177]
 [ 154  272 1076  218]
 [ 327   89   39 1302]]
n_estimators = 65
[[ 846  277  200  293]
 [ 365  578  452  177]
 [ 154  272 1076  218]
 [ 327   89   39 1302]]
n_estimators = 65
[[ 846  277  200  293]
 [ 365  578  452  177]
 [ 154  272 1076  218]
 [ 327   89   39 1302]]
n_estimators = 65
[[ 846  277  200  293]
 [ 365  578  452  177]
 [ 154  272 1076  218]
 [ 327   89   39 1302]]
n_estimators = 65
[[ 846  277  200  293]
 [ 365  578  452  177]
 [ 154  272 1076  218]
 [ 327   89   39 1302]]
n_estimators = 65
[[ 846  277  200  293]
 [ 365  578  452  177]
 [ 154  272 1076  218]
 [ 327   89   39 1302]]
n_estimators = 65
[

n_estimators = 69
[[ 851  279  195  291]
 [ 359  588  444  181]
 [ 155  273 1076  216]
 [ 320   90   39 1308]]
n_estimators = 69
[[ 851  279  195  291]
 [ 359  588  444  181]
 [ 155  273 1076  216]
 [ 320   90   39 1308]]
n_estimators = 69
[[ 851  279  195  291]
 [ 359  588  444  181]
 [ 155  273 1076  216]
 [ 320   90   39 1308]]
n_estimators = 69
[[ 851  279  195  291]
 [ 359  588  444  181]
 [ 155  273 1076  216]
 [ 320   90   39 1308]]
n_estimators = 69
[[ 851  279  195  291]
 [ 359  588  444  181]
 [ 155  273 1076  216]
 [ 320   90   39 1308]]
n_estimators = 69
[[ 851  279  195  291]
 [ 359  588  444  181]
 [ 155  273 1076  216]
 [ 320   90   39 1308]]
n_estimators = 69
[[ 851  279  195  291]
 [ 359  588  444  181]
 [ 155  273 1076  216]
 [ 320   90   39 1308]]
n_estimators = 69
[[ 851  279  195  291]
 [ 359  588  444  181]
 [ 155  273 1076  216]
 [ 320   90   39 1308]]
n_estimators = 69
[[ 851  279  195  291]
 [ 359  588  444  181]
 [ 155  273 1076  216]
 [ 320   90   39 1308]]
n

n_estimators = 72
[[ 860  276  191  289]
 [ 355  591  443  183]
 [ 156  275 1076  213]
 [ 315   90   40 1312]]
n_estimators = 72
[[ 860  276  191  289]
 [ 355  591  443  183]
 [ 156  275 1076  213]
 [ 315   90   40 1312]]
n_estimators = 72
[[ 860  276  191  289]
 [ 355  591  443  183]
 [ 156  275 1076  213]
 [ 315   90   40 1312]]
n_estimators = 72
[[ 860  276  191  289]
 [ 355  591  443  183]
 [ 156  275 1076  213]
 [ 315   90   40 1312]]
n_estimators = 72
[[ 860  276  191  289]
 [ 355  591  443  183]
 [ 156  275 1076  213]
 [ 315   90   40 1312]]
n_estimators = 73
[[ 859  277  191  289]
 [ 353  595  441  183]
 [ 153  279 1074  214]
 [ 321   89   40 1307]]
n_estimators = 73
[[ 859  277  191  289]
 [ 353  595  441  183]
 [ 153  279 1074  214]
 [ 321   89   40 1307]]
n_estimators = 73
[[ 859  277  191  289]
 [ 353  595  441  183]
 [ 153  279 1074  214]
 [ 321   89   40 1307]]
n_estimators = 73
[[ 859  277  191  289]
 [ 353  595  441  183]
 [ 153  279 1074  214]
 [ 321   89   40 1307]]
n

n_estimators = 76
[[ 865  275  187  289]
 [ 360  591  439  182]
 [ 154  276 1078  212]
 [ 318   90   40 1309]]
n_estimators = 76
[[ 865  275  187  289]
 [ 360  591  439  182]
 [ 154  276 1078  212]
 [ 318   90   40 1309]]
n_estimators = 76
[[ 865  275  187  289]
 [ 360  591  439  182]
 [ 154  276 1078  212]
 [ 318   90   40 1309]]
n_estimators = 76
[[ 865  275  187  289]
 [ 360  591  439  182]
 [ 154  276 1078  212]
 [ 318   90   40 1309]]
n_estimators = 76
[[ 865  275  187  289]
 [ 360  591  439  182]
 [ 154  276 1078  212]
 [ 318   90   40 1309]]
n_estimators = 76
[[ 865  275  187  289]
 [ 360  591  439  182]
 [ 154  276 1078  212]
 [ 318   90   40 1309]]
n_estimators = 76
[[ 865  275  187  289]
 [ 360  591  439  182]
 [ 154  276 1078  212]
 [ 318   90   40 1309]]
n_estimators = 76
[[ 865  275  187  289]
 [ 360  591  439  182]
 [ 154  276 1078  212]
 [ 318   90   40 1309]]
n_estimators = 76
[[ 865  275  187  289]
 [ 360  591  439  182]
 [ 154  276 1078  212]
 [ 318   90   40 1309]]
n

[[ 865  273  188  290]
 [ 356  592  441  183]
 [ 154  273 1080  213]
 [ 314   89   42 1312]]
n_estimators = 80
[[ 865  273  188  290]
 [ 356  592  441  183]
 [ 154  273 1080  213]
 [ 314   89   42 1312]]
n_estimators = 80
[[ 865  273  188  290]
 [ 356  592  441  183]
 [ 154  273 1080  213]
 [ 314   89   42 1312]]
n_estimators = 80
[[ 865  273  188  290]
 [ 356  592  441  183]
 [ 154  273 1080  213]
 [ 314   89   42 1312]]
n_estimators = 80
[[ 865  273  188  290]
 [ 356  592  441  183]
 [ 154  273 1080  213]
 [ 314   89   42 1312]]
n_estimators = 80
[[ 865  273  188  290]
 [ 356  592  441  183]
 [ 154  273 1080  213]
 [ 314   89   42 1312]]
n_estimators = 80
[[ 865  273  188  290]
 [ 356  592  441  183]
 [ 154  273 1080  213]
 [ 314   89   42 1312]]
n_estimators = 80
[[ 865  273  188  290]
 [ 356  592  441  183]
 [ 154  273 1080  213]
 [ 314   89   42 1312]]
n_estimators = 80
[[ 865  273  188  290]
 [ 356  592  441  183]
 [ 154  273 1080  213]
 [ 314   89   42 1312]]
n_estimators = 80
[

KeyboardInterrupt: 

In [25]:
YY[1000:1020]

array([2., 3., 2., 3., 3., 2., 2., 2., 2., 3., 4., 1., 3., 2., 3., 1., 1.,
       4., 4., 3.])

In [27]:
x_new = XX[1000:1020]
lst_3 = list(range(50,200))
k = []
for s in lst_3:
  model=GradientBoostingClassifier(n_estimators = s, random_state = 7)
  model.fit(X,Y)
  res = model.predict(x_new)
  print(f'n_estimators:{s} предсказание: {res}')
  k.append(res)

n_estimators:50 предсказание: [1. 3. 3. 3. 4. 3. 1. 4. 2. 1. 1. 4. 3. 1. 4. 4. 3. 4. 4. 2.]
n_estimators:51 предсказание: [1. 3. 3. 3. 4. 3. 1. 4. 2. 1. 1. 4. 3. 1. 4. 4. 3. 4. 4. 2.]
n_estimators:52 предсказание: [1. 3. 3. 3. 4. 3. 1. 4. 2. 1. 1. 4. 3. 1. 4. 4. 3. 4. 4. 2.]
n_estimators:53 предсказание: [1. 3. 3. 3. 4. 3. 1. 4. 2. 1. 1. 4. 3. 1. 4. 4. 3. 4. 4. 2.]
n_estimators:54 предсказание: [1. 3. 3. 3. 4. 3. 1. 4. 2. 1. 1. 4. 3. 1. 4. 4. 3. 4. 4. 2.]
n_estimators:55 предсказание: [1. 3. 3. 3. 4. 3. 1. 4. 2. 1. 1. 4. 3. 1. 4. 4. 3. 4. 4. 2.]
n_estimators:56 предсказание: [1. 3. 3. 3. 4. 3. 1. 4. 2. 1. 1. 4. 3. 1. 4. 4. 3. 4. 4. 2.]
n_estimators:57 предсказание: [1. 3. 3. 3. 4. 3. 1. 4. 2. 1. 1. 4. 3. 1. 4. 4. 3. 4. 4. 2.]
n_estimators:58 предсказание: [1. 3. 3. 3. 4. 3. 1. 4. 2. 1. 1. 4. 3. 1. 4. 4. 3. 4. 4. 2.]
n_estimators:59 предсказание: [1. 3. 3. 3. 4. 3. 1. 4. 2. 1. 1. 4. 3. 1. 4. 4. 3. 4. 4. 2.]
n_estimators:60 предсказание: [1. 3. 3. 3. 4. 3. 1. 4. 2. 1. 1. 4. 3. 1. 4. 4. 3

KeyboardInterrupt: 

In [ ]:
=============================================================================================================

In [1]:
import pandas as pd
import numpy as np
from pandas import read_csv

In [2]:
df=read_csv('D:\Политех\Класиффикация\Сегментация_клиентов\Train_cleared_!!!!!!!!.csv')

In [3]:
df=df.filter(regex='^(?!.*Unnamed).*$')

In [4]:
df_T=read_csv('D:\Политех\Класиффикация\Сегментация_клиентов\Test_cleared_!!!!!!!!.csv')

In [5]:
df_T=df_T.filter(regex='^(?!.*Unnamed).*$')

**Обучающий_набор**

In [6]:
array = df.values
array
X = array[:,0:9]
Y = array[:,9]

**Тестовый_набор**

In [7]:
array_T = df_T.values
array_T
XX = array_T[:,0:9]
YY = array_T[:,9]

In [8]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
# отбор признаков:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
# ансамблевые функции:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
import numpy as np
from sklearn.linear_model import RidgeClassifier
from sklearn.model_selection import GridSearchCV
from scipy.stats import uniform
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import train_test_split
# сохраняет параметры после перезагрузки:
import pickle
import joblib

In [ ]:
========================================================================================================================

# **GrideSearchCV**

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsClassifier

In [10]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, shuffle=True, random_state=7) 

In [11]:
clf = GradientBoostingClassifier()

In [15]:
params = {
            "loss":["deviance"],
            "learning_rate": [0.01,  0.05,  0.1,  0.2],
            "min_samples_split": np.linspace(0.1, 0.5, 6),
            "min_samples_leaf": np.linspace(0.1, 0.5, 6),
            "max_depth":[3,5,8],
            "max_features":["log2","sqrt"],
            "criterion": ["friedman_mse",  "mae"],
            "subsample":[0.5,  0.8,  0.9,  1.0],
            "n_estimators":[10]
            }

In [16]:
grid = GridSearchCV(clf, param_grid = params, cv=3,verbose=1,n_jobs=-1)

In [17]:
grid.fit(X_train,Y_train)

Fitting 3 folds for each of 6912 candidates, totalling 20736 fits


GridSearchCV(cv=3, estimator=GradientBoostingClassifier(), n_jobs=-1,
             param_grid={'criterion': ['friedman_mse', 'mae'],
                         'learning_rate': [0.01, 0.05, 0.1, 0.2],
                         'loss': ['deviance'], 'max_depth': [3, 5, 8],
                         'max_features': ['log2', 'sqrt'],
                         'min_samples_leaf': array([0.1 , 0.18, 0.26, 0.34, 0.42, 0.5 ]),
                         'min_samples_split': array([0.1 , 0.18, 0.26, 0.34, 0.42, 0.5 ]),
                         'n_estimators': [10],
                         'subsample': [0.5, 0.8, 0.9, 1.0]},
             verbose=1)

In [18]:
print(grid.best_params_)
print(grid.best_estimator_)

{'criterion': 'friedman_mse', 'learning_rate': 0.2, 'loss': 'deviance', 'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 0.1, 'min_samples_split': 0.1, 'n_estimators': 10, 'subsample': 1.0}
GradientBoostingClassifier(learning_rate=0.2, max_depth=5, max_features='log2',
                           min_samples_leaf=0.1, min_samples_split=0.1,
                           n_estimators=10)


In [19]:
from sklearn.metrics import classification_report, confusion_matrix

In [20]:
grid_predictions = grid.predict(X_test)
print(classification_report(Y_test, grid_predictions))

              precision    recall  f1-score   support

         1.0       0.48      0.47      0.48       351
         2.0       0.41      0.36      0.38       347
         3.0       0.54      0.53      0.54       361
         4.0       0.60      0.70      0.64       373

    accuracy                           0.52      1432
   macro avg       0.51      0.51      0.51      1432
weighted avg       0.51      0.52      0.51      1432



In [21]:
print(confusion_matrix(Y_test, grid_predictions))

[[166  69  45  71]
 [ 73 124 106  44]
 [ 35  73 191  62]
 [ 69  34   9 261]]


In [ ]:
================================================================================================================

In [23]:
model = GradientBoostingClassifier(learning_rate=0.2, max_depth=5, max_features='log2',
                           min_samples_leaf=0.1, min_samples_split=0.1,
                           n_estimators=10)

In [28]:
model = GradientBoostingClassifier()

In [29]:
model.fit(X_train,Y_train)

GradientBoostingClassifier()

In [30]:
new_predictions = model.predict(X_test)

In [31]:
print(classification_report(Y_test, new_predictions))
print(confusion_matrix(Y_test, new_predictions))

              precision    recall  f1-score   support

         1.0       0.46      0.45      0.45       351
         2.0       0.41      0.38      0.39       347
         3.0       0.56      0.53      0.55       361
         4.0       0.60      0.69      0.64       373

    accuracy                           0.51      1432
   macro avg       0.51      0.51      0.51      1432
weighted avg       0.51      0.51      0.51      1432

[[157  83  40  71]
 [ 75 131  96  45]
 [ 38  73 193  57]
 [ 70  30  17 256]]


In [ ]:
================================================================================================================

In [32]:
kfold=KFold(n_splits=3,random_state=7,shuffle=True)
results=cross_val_score(model, X, Y, cv=3)
results.mean()

0.5128339444735462

In [ ]:
# без параметров лучше получается