In [59]:
import pandas as pd
import numpy as np
from pandas import read_csv

In [60]:
df=read_csv('D:\Политех\Класиффикация\Сегментация_клиентов\Train_cleared_dropna.csv')

In [61]:
df_T=read_csv('D:\Политех\Класиффикация\Сегментация_клиентов\TEST_cleared_dropna.csv')

In [62]:
df=df.filter(regex='^(?!.*Unnamed).*$')

In [63]:
df_T=df_T.filter(regex='^(?!.*Unnamed).*$')

================================================================

**Обучающий_набор**

In [64]:
array = df.values
array

array([[ 1.,  0., 22., ...,  4.,  4.,  4.],
       [ 0.,  1., 67., ...,  1.,  6.,  2.],
       [ 1.,  1., 67., ...,  2.,  6.,  2.],
       ...,
       [ 0.,  0., 33., ...,  1.,  6.,  4.],
       [ 0.,  0., 27., ...,  4.,  6.,  2.],
       [ 1.,  1., 37., ...,  3.,  4.,  2.]])

In [65]:
X = array[:,0:9]
Y = array[:,9]

In [66]:
X

array([[ 1.,  0., 22., ...,  3.,  4.,  4.],
       [ 0.,  1., 67., ...,  3.,  1.,  6.],
       [ 1.,  1., 67., ...,  1.,  2.,  6.],
       ...,
       [ 0.,  0., 33., ...,  3.,  1.,  6.],
       [ 0.,  0., 27., ...,  3.,  4.,  6.],
       [ 1.,  1., 37., ...,  2.,  3.,  4.]])

In [67]:
Y

array([4., 2., 2., ..., 4., 2., 2.])

==============================================================

**Тестовый_набор**

In [68]:
array_T = df.values
array_T

array([[ 1.,  0., 22., ...,  4.,  4.,  4.],
       [ 0.,  1., 67., ...,  1.,  6.,  2.],
       [ 1.,  1., 67., ...,  2.,  6.,  2.],
       ...,
       [ 0.,  0., 33., ...,  1.,  6.,  4.],
       [ 0.,  0., 27., ...,  4.,  6.,  2.],
       [ 1.,  1., 37., ...,  3.,  4.,  2.]])

In [69]:
XX = array_T[:,0:9]
YY = array_T[:,9]

In [70]:
XX

array([[ 1.,  0., 22., ...,  3.,  4.,  4.],
       [ 0.,  1., 67., ...,  3.,  1.,  6.],
       [ 1.,  1., 67., ...,  1.,  2.,  6.],
       ...,
       [ 0.,  0., 33., ...,  3.,  1.,  6.],
       [ 0.,  0., 27., ...,  3.,  4.,  6.],
       [ 1.,  1., 37., ...,  2.,  3.,  4.]])

In [13]:
YY

array([4., 2., 2., ..., 4., 2., 2.])

=====================================================

In [71]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
# отбор признаков:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
# ансамблевые функции:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
import numpy as np
from sklearn.linear_model import RidgeClassifier
from sklearn.model_selection import GridSearchCV
from scipy.stats import uniform
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import train_test_split
# сохраняет параметры после перезагрузки:
import pickle
import joblib

In [18]:
+++++++++++++++++++++++++++++++++++++++++++++++++++++

SyntaxError: invalid syntax (Temp/ipykernel_17880/441078461.py, line 1)

**Выделяем 3 выборки: обучающую, валидационную и тестовую**

In [88]:
X_train_test, X_val, Y_train_test, Y_val = train_test_split(X, Y, test_size=0.25, random_state= 7, shuffle=True)

In [89]:
X_train, X_test, Y_train, Y_test = train_test_split(X_train_test, Y_train_test, test_size=0.25, shuffle=True, random_state=7) 

In [48]:
alphas = np.array([7,5,3,1,0.1,0.01,0.001,0.0001,0])

In [49]:
param_grid = dict(alpha=alphas)

In [50]:
model = RidgeClassifier()

In [51]:
grid = GridSearchCV(estimator = model, param_grid = param_grid, cv = 3)

In [52]:
grid.fit(X_val, Y_val)

GridSearchCV(cv=3, estimator=RidgeClassifier(),
             param_grid={'alpha': array([7.e+00, 5.e+00, 3.e+00, 1.e+00, 1.e-01, 1.e-02, 1.e-03, 1.e-04,
       0.e+00])})

In [53]:
grid.best_score_

0.44030613347160114

In [54]:
grid.best_estimator_.alpha

3.0

In [55]:
model = RidgeClassifier(alpha=grid.best_estimator_.alpha)

In [56]:
model.fit(X_test, Y_test)

RidgeClassifier(alpha=3.0)

In [58]:
model.score(X_test, Y_test)

0.4912

In [71]:
kfold = KFold(n_splits= 3, random_state = 7, shuffle=True)

In [72]:
estimators = []

In [73]:
estimators.append(('logistic', LogisticRegression()))

In [74]:
estimators.append(('cart', DecisionTreeClassifier()))

In [75]:
estimators.append(('svm', SVC()))

In [76]:
estimators

[('logistic', LogisticRegression()),
 ('cart', DecisionTreeClassifier()),
 ('svm', SVC())]

In [83]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler().fit(X)
rescaledX=scaler.transform(X)

In [84]:
ensemble = VotingClassifier(estimators)

In [85]:
results = cross_val_score(ensemble, rescaledX, Y, cv=kfold)

In [86]:
results.mean(), results.std()

(0.5077266168760054, 0.008761881023465708)

In [90]:
X_train_test, X_val, Y_train_test, Y_val = train_test_split(X, Y, test_size=0.25, random_state= 7)

In [91]:
param_grid = {'alpha':uniform()}

In [92]:
model = RidgeClassifier()

In [93]:
rsearch = RandomizedSearchCV(estimator = model, param_distributions = param_grid, n_iter = 100, cv = 3, random_state = 7)

In [94]:
rsearch.fit(X_val,Y_val)

RandomizedSearchCV(cv=3, estimator=RidgeClassifier(), n_iter=100,
                   param_distributions={'alpha': <scipy.stats._distn_infrastructure.rv_frozen object at 0x00000174EB969190>},
                   random_state=7)

In [95]:
rsearch.best_score_

0.43910709270421505

In [96]:
rsearch.best_estimator_.alpha

0.07630828937395717

In [97]:
model = RidgeClassifier(alpha=rsearch.best_estimator_.alpha)

In [98]:
model.fit(X_test, Y_test)

RidgeClassifier(alpha=0.07630828937395717)

In [99]:
model.score(X_test, Y_test)

0.4912