# **Чем ящик с усами уже и среднее выше на графике, тем метод лучше**

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

import os
#import numpy as np
#import pandas as pd
from pandas import read_csv
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import FeatureUnion
from sklearn.decomposition import PCA
from sklearn.feature_selection import SelectKBest

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
from sklearn.pipeline import Pipeline

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
from sklearn.linear_model import Ridge

In [ ]:
from sklearn.linear_model import Lasso

In [ ]:
from sklearn.linear_model import ElasticNet

In [ ]:
estimators=[]

In [ ]:
estimators.append(('standardize',StandardScaler()))

In [ ]:
estimators.append(('DTree',DecisionTreeRegressor()))

In [ ]:
model=Pipeline(estimators)

In [ ]:
kfold=KFold(n_splits = 10, random_state = 7, shuffle = True)

In [ ]:
results=cross_val_score(model, X, Y, cv=kfold, scoring=scoring)

# **Раздел 4. Создание пайплайна (программного конвеера) для отбора признаков и моделирования**

In [ ]:
features = []

In [ ]:
features.append(('pca',PCA(n_components=4)))

In [ ]:
features.append(('select_best',SelectKBest(k=6)))

In [ ]:
features_union=FeatureUnion(features)

In [ ]:
estimators=[]

In [ ]:
estimators.append(('feature_union',features_union))

In [ ]:
estimators.append(('LinRegr',LinearRegression()))

In [ ]:
model=Pipeline(estimators)

In [ ]:
kfold=KFold(n_splits = 10, random_state = 7, shuffle = True)

In [ ]:
results=cross_val_score(model, X, Y, cv=kfold, scoring=scoring)

In [ ]:
results.mean()

-0.005249407778667196

In [ ]:
results.std()

0.0012392648670512135

# **ЗАДАНИЕ 7. ЛИНЕЙНЫЕ МОДЕЛИ ДЛЯ КЛАССИФИКАЦИИ**

Постройте линейные модели для классификации (логистическая регрессия, линейный метод опорных векторов, линейный дискриминантный анализ), оцените их качество, дайте прогноз класса для нового наблюдения.
Постарайтесь максимально автоматизировать все вычисления, использовать существующие модули среды программирования Python.

# **Методика выполнения задания:**

# **Раздел 1. Логистическая регрессия (функция)**

**1. Укажите путь к рабочей папке, где хранятся данные, с помощью функции chdir() из модуля os.**

**2. Загрузите данные файла pima-indians-diabetes.data.csv с помощью функции read_csv() из модуля pandas. Названия столбцов укажите следующими: names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']. Посмотрите на первые 5 наблюдений с помощью функции head().**

**3. Сохраните в переменную array значения признаков, обратившись к атрибуту values.**

**4. Выделите в переменной array часть, которая относится к факторным признакам, назовите ее X, и часть, которая относится к результативному признаку, - Y. Прокомментируйте содержимое переменных X и Y.**


In [ ]:
os.chdir('/content/gdrive/MyDrive/Colab Notebooks/PDA-200')

In [ ]:
filename='housing.csv'
names=['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO','B', 'LSTAT', 'MEDV']
data=read_csv(filename, delim_whitespace=True, names=names)
data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

**3. Сохраните в переменную array значения признаков, обратившись к атрибуту values.**

In [ ]:
array = data.values
array

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 3.9690e+02, 4.9800e+00,
        2.4000e+01],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 3.9690e+02, 9.1400e+00,
        2.1600e+01],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 3.9283e+02, 4.0300e+00,
        3.4700e+01],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 5.6400e+00,
        2.3900e+01],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 3.9345e+02, 6.4800e+00,
        2.2000e+01],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 7.8800e+00,
        1.1900e+01]])

In [ ]:
array = data.values
array

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 3.9690e+02, 4.9800e+00,
        2.4000e+01],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 3.9690e+02, 9.1400e+00,
        2.1600e+01],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 3.9283e+02, 4.0300e+00,
        3.4700e+01],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 5.6400e+00,
        2.3900e+01],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 3.9345e+02, 6.4800e+00,
        2.2000e+01],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 7.8800e+00,
        1.1900e+01]])

In [ ]:
X = array[:,0:4] # факторные признаки, т.е. параметры объекта
Y = array[:,4] # результативные признак, т.е. сам объект
# это обучение с учителем х - это данные, y - это ответ

In [ ]:
Y

**5. Задайте разбиение на фолды с помощью функции KFold(n_splits= n_splits, random_state = random_state, shuffle=True) из модуля sklearn.model_selection. Результат запишите в переменную kfold. На вход данной функции подайте следующую информацию: 1) количество частей, на которые должна разбиваться выборка (n_splits), - пусть 10; 2) счетчик случайных чисел (random_state) – пусть 7; 3) необходимость перемешивания данных выборки при каждой оценке, задав параметр shuffle=True.**

In [ ]:
kfold=KFold(n_splits=10,random_state=7,shuffle=True)

In [ ]:
scoring = 'neg_mean_squared_error'

**6. Постройте модель логистической регрессии, воспользовавшись функцией LogisticRegression(solver='liblinear') из модуля sklearn.linear_model. Результат запишите в переменную model.**

In [ ]:
model=KNeighborsRegressor()

**7. Проведите кросс-валидацию, воспользовавшись функцией cross_val_score(model, X, Y, cv=kfold) из модуля sklearn.model_selection. Результат запишите в переменную results.**

In [ ]:
results=cross_val_score(model, X, Y, cv=kfold, scoring=scoring)

**8. Выведите на экран среднюю долю правильных ответов (accuracy) и стандартное отклонение полученных оценок, воспользовавшись функциями mean() и std() соответственно.**

In [ ]:
results.mean()

-0.003005155845270588

In [ ]:
results.std()

0.0007388680203435243

**9. Обучите модель на всех данных с помощью функции fit().**

**10. Выведите на экран свободный член и значения коэффициентов регрессии при факторных признаках, которая разделяет классы, обратившись, соответственно, к атрибутам intercept_shape и coef_shape. Запишите математически уравнение регрессии.**

In [ ]:
model.fit(X,Y)

LogisticRegression(solver='liblinear')

In [ ]:
model.intercept_.shape

(3,)

In [ ]:
model.coef_.shape

(3, 4)

In [ ]:
model.intercept_

array([ 0.26560617,  1.08542374, -1.21471458])

In [ ]:
model.coef_

array([[ 0.41498833,  1.46129739, -2.26214118, -1.0290951 ],
       [ 0.41663969, -1.60083319,  0.57765763, -1.38553843],
       [-1.70752515, -1.53426834,  2.47097168,  2.55538211]])

**11. Произвольно задайте значения факторных признаков для двух новых наблюдений. Поместите их в переменную x_new. Например, np.array([[0,136,42,34,136,43,2,32],[0,137,40,35,168,43.1,2.288,33]]).**

**12. По обученной модели дайте прогноз классов для новых наблюдений, воспользовавшись функцией predict().**


In [ ]:
df.sample(8)

sepal length  sepal width  petal length  petal width            class
70            5.9          3.2           4.8          1.8  Iris-versicolor
57            4.9          2.4           3.3          1.0  Iris-versicolor
18            5.7          3.8           1.7          0.3      Iris-setosa
76            6.8          2.8           4.8          1.4  Iris-versicolor
14            5.8          4.0           1.2          0.2      Iris-setosa
65            6.7          3.1           4.4          1.4  Iris-versicolor
5             5.4          3.9           1.7          0.4      Iris-setosa
118           7.7          2.6           6.9          2.3   Iris-virginica

In [ ]:
x_new=np.array([[6.8,3.3,5.8,1.2],[5.1,3.1,4.1,2.2]])
# это данные 2-х пациентов щас проверим заболеют или нет

In [ ]:
model.predict(x_new)
# подставляем наши данные в обученную модель и смотрим что
# исходя из параметров пациенты скорей всего заболеют, т.е.
# их можно отнести к группе риска

array(['Iris-versicolor', 'Iris-virginica'], dtype='<U15')

**13. По обученной модели дайте прогноз вероятности классов для новых наблюдений, воспользовавшись функцией predict_proba().**

In [ ]:
model.predict_proba(x_new)
# нулевой столбец - это нулевой класс
# первый столбец - это первый класс

# делаем вывод:
# вероятность, что пациент не заболеет 20%,
# а то, что заболеет 80%

array([[1.42408012e-26, 9.71251871e-01, 2.87481289e-02],
       [1.96176037e-30, 1.00098359e-02, 9.89990164e-01]])

# **Раздел 2. Линейный метод опорных векторов**

**14. Постройте модель линейного метода опорных векторов, воспользовавшись функцией SVC(kernel='linear') из модуля sklearn.svm. Результат запишите в переменную model.**

**15. Проведите кросс-валидацию, воспользовавшись функцией cross_val_score(model, X, Y, cv=kfold) из модуля sklearn.model_selection. Результат запишите в переменную results.**  

**16. Выведите на экран среднюю долю правильных ответов (accuracy) и стандартное отклонение полученных оценок, воспользовавшись функциями mean() и std() соответственно.**


In [ ]:
model=SVC(kernel='linear')

In [ ]:
results=cross_val_score(model, X, Y, cv=kfold)

In [ ]:
results.mean(),results.std()

(0.9733333333333334, 0.03265986323710903)

**17. Обучите модель на всех данных с помощью функции fit().**

**18. Выведите на экран свободный член и значения коэффициентов регрессии при факторных признаках, которая разделяет классы, обратившись, соответственно, к атрибутам intercept_ и coef_. Запишите**

In [ ]:
model.fit(X,Y)

SVC(kernel='linear')

In [ ]:
model.intercept_.shape

(3,)

In [ ]:
model.coef_.shape

(3, 4)

In [ ]:
model.intercept_

array([1.4528445 , 1.50771313, 6.78097119])

In [ ]:
model.coef_

array([[-0.04625854,  0.5211828 , -1.00304462, -0.46412978],
       [-0.00722313,  0.17894121, -0.53836459, -0.29239263],
       [ 0.59549776,  0.9739003 , -2.03099958, -2.00630267]])

**19. По обученной модели дайте прогноз классов для новых наблюдений, заданных в п. 11, воспользовавшись функцией predict().**


In [ ]:
x_new=np.array([[6.8,3.3,5.8,1.2],[5.1,3.1,4.1,2.2]])
model.predict(x_new)

array(['Iris-virginica', 'Iris-versicolor'], dtype=object)

**20. В методе опорных векторов смените ядро с 'linear' на 'rbf'. Метод станет нелинейным. Обучите новую модель и дайте прогноз классов для новых наблюдений, заданных в п. 11.**


In [ ]:
model=SVC(kernel='rbf')

In [ ]:
results=cross_val_score(model, X, Y, cv=kfold)

In [ ]:
results.mean(),results.std()

(0.9600000000000002, 0.053333333333333316)

In [ ]:
model.fit(X,Y)

SVC()

In [ ]:
model.predict(x_new)

array(['Iris-virginica', 'Iris-versicolor'], dtype=object)

# **Раздел 3. Линейный дискриминантный анализ**

**21. Проверьте многомерную нормальность закона распределения дискриминантных переменных с помощью функции multivariate_normality(X, alpha=.05) из модуля pingouin, который удобно сокращенно называть pg. В функции реализован Henze-Zirkler Multivariate Normality Test. Прокомментируйте результат.**

In [ ]:
import pingouin as pg

In [ ]:
pg.multivariate_normality(X, alpha=.05) # распределено ненормально, фигово

**22. Проверьте нормальность распределения каждого из признаков из набора данных, воспользовавшись функцией normality(dataframe) из модуля pingouin. В функции реализован тест Шапиро-Уилка. Прокомментируйте результат. Можно ли добиться многомерной нормальности распределения дискриминантных переменных?**


In [ ]:
pg.normality(df) # все признаки ненормальные, фигово

W          pval  normal
sepal length  0.976090  1.017984e-02   False
sepal width   0.983792  7.518344e-02    True
petal length  0.876424  7.544982e-10   False
petal width   0.902624  1.864668e-08   False

**23. Проверьте приблизительное равенство между ковариационными матрицами для каждого класса на основе критерия M Бокса, воспользовавшись функцией box_m(dataframe, dvs=['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age'], group='class') из модуля pingouin. Прокомментируйте результат.**

In [ ]:
pg.box_m(df, dvs=['sepal length','sepal width','petal length','petal width'], group='class')
# опять фигово

Chi2    df          pval  equal_cov
box  139.236945  20.0  7.062101e-20      False

**24. Проверьте линейную независимость дискриминантных переменных на основе коэффициента корреляции Пирсона, воспользовавшись функцией pairwise_corr(dataframe, columns=['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age'], method='pearson') из модуля pingouin. Прокомментируйте результат.**

In [ ]:
# p-unc - это p-value
# [0] гипотеза - коэффициент корреляции = 0

In [ ]:
pg.pairwise_corr(df, columns=['sepal length','sepal width','petal length','petal width'], method='pearson')

X             Y   method alternative    n         r  \
0  sepal length   sepal width  pearson   two-sided  150 -0.109369   
1  sepal length  petal length  pearson   two-sided  150  0.871754   
2  sepal length   petal width  pearson   two-sided  150  0.817954   
3   sepal width  petal length  pearson   two-sided  150 -0.420516   
4   sepal width   petal width  pearson   two-sided  150 -0.356544   
5  petal length   petal width  pearson   two-sided  150  0.962757   

            CI95%         p-unc       BF10     power  
0   [-0.26, 0.05]  1.827652e-01      0.246  0.266452  
1    [0.83, 0.91]  1.038454e-47  1.811e+44  1.000000  
2    [0.76, 0.86]  2.314849e-37  1.189e+34  1.000000  
3  [-0.54, -0.28]  8.429366e-08  1.517e+05  0.999760  
4  [-0.49, -0.21]  7.523891e-06   2095.959  0.994989  
5    [0.95, 0.97]  5.776661e-86  9.038e+81  1.000000

**26. Несмотря на вывод в п.25, с целью знакомства с возможностями модуля sklearn, постройте модель линейного дискриминантного анализа, воспользовавшись функцией LinearDiscriminantAnalysis() из модуля sklearn.discriminant_analysis. Результат запишите в переменную model.**

**27. Проведите кросс-валидацию, воспользовавшись функцией cross_val_score(model, X, Y, cv=kfold) из модуля sklearn.model_selection. Результат запишите в переменную results.**  

**28. Выведите на экран среднюю долю правильных ответов (accuracy) и стандартное отклонение полученных оценок, воспользовавшись, соответственно, функциями mean() и std().**


In [ ]:
model=LinearDiscriminantAnalysis()

In [ ]:
results=cross_val_score(model, X, Y, cv=kfold)

In [ ]:
results.mean(),results.std()

(0.9800000000000001, 0.030550504633038926)

**29. Обучите модель на всех данных с помощью функции fit().**

**30. По обученной модели дайте прогноз классов для новых наблюдений, заданных в п. 11, воспользовавшись функцией predict().**

In [ ]:
model.fit(X,Y)

LinearDiscriminantAnalysis()

In [ ]:
model.predict(x_new)

array(['Iris-versicolor', 'Iris-virginica'], dtype='<U15')

**31. По обученной модели дайте прогноз вероятности классов для новых наблюдений, воспользовавшись функцией predict_proba().**

In [ ]:
model.predict_proba(x_new)

array([[1.42408012e-26, 9.71251871e-01, 2.87481289e-02],
       [1.96176037e-30, 1.00098359e-02, 9.89990164e-01]])

**32. Рассчитайте значения дискриминантных функций, обратившись к функции transform(X). Выведите на экран первые 5 наблюдений.**

In [ ]:
model.transform(X)[0:5]

array([[ 8.0849532 ,  0.32845422],
       [ 7.1471629 , -0.75547326],
       [ 7.51137789, -0.23807832],
       [ 6.83767561, -0.64288476],
       [ 8.15781367,  0.54063935]])

**33. Убедитесь в том, что функция fit_transform(X,Y) дает тот же результат. Выведите на экран первые 5 наблюдений.**


In [ ]:
model.fit_transform(X,Y)[0:5]

array([[ 8.0849532 ,  0.32845422],
       [ 7.1471629 , -0.75547326],
       [ 7.51137789, -0.23807832],
       [ 6.83767561, -0.64288476],
       [ 8.15781367,  0.54063935]])

**34. Какому методу прогнозирования Вы доверяете больше? Какой прогноз примете в качестве окончательного?**

In [ ]:
# Логистическая регрессия (функция)