In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
import os
import numpy as np
import pandas as pd
from pandas import read_csv
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.svm import SVC

In [ ]:
os.chdir('/content/gdrive/MyDrive/Colab Notebooks/наборы данных')

In [ ]:
filename='metro_tr_очищен3.csv'
#names=['area A','perimeter P','compactness','length of ker',
#       'width of ker', 'asymmetry coeff', 'length of ker groove','class']
df=read_csv(filename)#,sep='\t', error_bad_lines=False,names=names)

In [ ]:
df.dtypes

Unnamed: 0               int64
temp                   float64
clouds_all             float64
weather_main           float64
weather_description    float64
month                  float64
hour                   float64
end                      int64
dtype: object

_________________________________________________________________________

# **ЛОГИСТИЧЕСКАЯ РЕГРЕССИЯ**

In [ ]:
df.sample(4)

Unnamed: 0  holiday     temp  rain_1h  snow_1h  clouds_all  \
27584       27584        7  285.949      0.0      0.0          88   
22287       22287        7  275.410      0.0      0.0          90   
28445       28445        7  274.090      0.0      0.0          90   
31573       31573        7  276.220      0.0      0.0           1   

       weather_main  weather_description  month  hour  traffic_volume  \
27584             1                   19     10    16            6087   
22287             1                   19      4    23             982   
28445             8                   16     11     2             474   
31573             0                   27      3    22            2816   

                date_time  
27584 2016-10-25 16:00:00  
22287 2016-04-06 23:00:00  
28445 2016-11-25 02:00:00  
31573 2017-03-07 22:00:00

In [ ]:
df.set_index('Unnamed: 0',inplace=True)

In [ ]:
df

temp  clouds_all  weather_main  weather_description  month  hour  \
Unnamed: 0                                                                     
0           0.55       -0.24         -0.57                 0.83   1.03 -0.35   
1           0.64        0.66         -0.57                -1.62   1.03 -0.20   
2           0.65        1.04         -0.57                 0.27   1.03 -0.06   
3           0.70        1.04         -0.57                 0.27   1.03  0.09   
4           0.78        0.66         -0.57                -1.62   1.03  0.23   
...          ...         ...           ...                  ...    ...   ...   
48189       0.17        0.66         -0.57                -1.62   0.73  1.10   
48190       0.12        1.04         -0.57                 0.27   0.73  1.24   
48191       0.12        1.04          2.67                 0.50   0.73  1.38   
48192       0.06        1.04         -0.57                 0.27   0.73  1.53   
48193       0.07        1.04         -0.57                 0.27   0.73  1.67   

             end  
Unnamed: 0        
0           5545  
1           4516  
2           4767  
3           5026  
4           4918  
...          ...  
48189       3543  
48190       2781  
48191       2159  
48192       1450  
48193        954  

[48194 rows x 7 columns]

In [ ]:
pd.set_option('precision', 2)

In [ ]:
df

temp  clouds_all  weather_main  weather_description  month  hour  \
Unnamed: 0                                                                     
0           0.55       -0.24         -0.57                 0.83   1.03 -0.35   
1           0.64        0.66         -0.57                -1.62   1.03 -0.20   
2           0.65        1.04         -0.57                 0.27   1.03 -0.06   
3           0.70        1.04         -0.57                 0.27   1.03  0.09   
4           0.78        0.66         -0.57                -1.62   1.03  0.23   
...          ...         ...           ...                  ...    ...   ...   
48189       0.17        0.66         -0.57                -1.62   0.73  1.10   
48190       0.12        1.04         -0.57                 0.27   0.73  1.24   
48191       0.12        1.04          2.67                 0.50   0.73  1.38   
48192       0.06        1.04         -0.57                 0.27   0.73  1.53   
48193       0.07        1.04         -0.57                 0.27   0.73  1.67   

             end  
Unnamed: 0        
0           5545  
1           4516  
2           4767  
3           5026  
4           4918  
...          ...  
48189       3543  
48190       2781  
48191       2159  
48192       1450  
48193        954  

[48194 rows x 7 columns]

In [ ]:
X = df.iloc[:1000,:6].values
X

array([[ 0.55, -0.24, -0.57,  0.83,  1.03, -0.35],
       [ 0.64,  0.66, -0.57, -1.62,  1.03, -0.2 ],
       [ 0.65,  1.04, -0.57,  0.27,  1.03, -0.06],
       ...,
       [-0.35,  1.04, -0.57,  0.27,  1.32,  1.67],
       [-0.35,  1.04, -0.57,  0.27,  1.32, -1.64],
       [-0.36,  1.04, -0.57,  0.27,  1.32, -1.5 ]])

In [ ]:
Y = df.iloc[:1000,6].values
Y

array([5545, 4516, 4767, 5026, 4918, 5181, 5584, 6015, 5791, 4770, 3539,
       2784, 2361, 1529,  963,  506,  321,  273,  367,  814, 2718, 5673,
       6511, 5471, 5097, 4887, 5337, 5692, 6137, 4623, 3591, 2898, 2637,
       1777, 1015,  598,  369,  312,  367,  835, 2726, 5689, 6990, 5985,
       5309, 4603, 4884, 5104, 5178, 5501, 5713, 6292, 6057, 4907, 3503,
       3037, 2822, 1992, 1166,  627,  388,  368, 2489, 5537, 6628, 5534,
       5403, 4770, 5217, 5870, 5967, 6108, 6128, 6069, 6169, 5384, 4063,
       3364, 2971, 2450, 1832, 1231,  718,  545,  411,  688, 1352, 2072,
       3342, 4258, 4861, 5191, 5669, 5074, 5025, 5153, 5024, 4779, 4362,
       3860, 3160, 2992, 3202, 1941, 1233,  323,  312,  627, 1508, 1539,
       2232, 4568, 4624, 4529, 5139, 6640, 6589, 4429, 4329, 3833, 4015,
       3382, 2815, 2110, 1555,  959,  455,  336,  265,  314,  779, 2571,
       5563, 6676, 5966, 4832, 4395, 4411, 4648, 4602, 5125, 5502, 5979,
       5663, 4259, 3069, 2378, 2030, 1400,  917,  5

In [ ]:
Y = df.iloc[:,7].values
Y

In [ ]:
pd.set_option('precision', 2)

In [ ]:
X = array[:,0:6] # факторные признаки, т.е. параметры объекта
Y = array[:,10] # результативные признак, т.е. сам объект
# это обучение с учителем х - это данные, y - это ответ

In [ ]:
X

array([5545, 4516, 4767, ..., 2159, 1450,  954])

In [ ]:
Y

array([5545, 4516, 4767, ..., 2159, 1450,  954])

**5. Задайте разбиение на фолды с помощью функции KFold(n_splits= n_splits, random_state = random_state, shuffle=True) из модуля sklearn.model_selection. Результат запишите в переменную kfold. На вход данной функции подайте следующую информацию: 1) количество частей, на которые должна разбиваться выборка (n_splits), - пусть 10; 2) счетчик случайных чисел (random_state) – пусть 7; 3) необходимость перемешивания данных выборки при каждой оценке, задав параметр shuffle=True.**

In [ ]:
kfold=KFold(n_splits=10,random_state=7,shuffle=True)

**6. Постройте модель логистической регрессии, воспользовавшись функцией LogisticRegression(solver='liblinear') из модуля sklearn.linear_model. Результат запишите в переменную model.**

In [ ]:
model=LogisticRegression(solver='liblinear')

In [ ]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [ ]:
r2 = model.score(X, Y)
r2

0.0825

**7. Проведите кросс-валидацию, воспользовавшись функцией cross_val_score(model, X, Y, cv=kfold) из модуля sklearn.model_selection. Результат запишите в переменную results.**

In [ ]:
results=cross_val_score(model, X, Y, cv=kfold) # cv - это количество раз разбивки данных на обучающий и тестовый наборы,обучение на них, тестирование и вывод обобщенного лучшего варианта

**8. Выведите на экран среднюю долю правильных ответов (accuracy) и стандартное отклонение полученных оценок, воспользовавшись функциями mean() и std() соответственно.**

In [ ]:
results.mean()

0.0

In [ ]:
results.std()

0.0

**9. Обучите модель на всех данных с помощью функции fit().**

**10. Выведите на экран свободный член и значения коэффициентов регрессии при факторных признаках, которая разделяет классы, обратившись, соответственно, к атрибутам intercept_shape и coef_shape. Запишите математически уравнение регрессии.**

In [ ]:
model.fit(X,Y)

LogisticRegression(solver='liblinear')

In [ ]:
model.intercept_.shape

(361,)

In [ ]:
model.coef_.shape

(361, 6)

In [ ]:
model.intercept_

In [ ]:
model.coef_

array([[-0.09215357, -0.13779438,  0.70995886, -0.27453013, -2.3129607 ,
        -0.35520618],
       [-0.25673659, -0.48205037,  0.58262395,  0.19028012, -2.30778032,
        -0.29022275],
       [-0.18092964, -0.48465823,  0.58042261,  0.18821208, -2.30963647,
        -0.30162586],
       ...,
       [-0.16853099, -0.50187038,  0.58074669,  0.19162756, -2.29270411,
        -0.11743893],
       [-0.3230572 , -0.13671787,  0.43541526, -0.35501619, -2.33106322,
        -0.13978621],
       [-0.42912686, -0.57190129,  0.63532449, -0.37329277, -2.28375072,
        -0.10095889]])

**11. Произвольно задайте значения факторных признаков для двух новых наблюдений. Поместите их в переменную x_new. Например, np.array([[0,136,42,34,136,43,2,32],[0,137,40,35,168,43.1,2.288,33]]).**

**12. По обученной модели дайте прогноз классов для новых наблюдений, воспользовавшись функцией predict().**


In [ ]:
Y_pred = model.predict(X)
# подставляем наши данные в обученную модель и смотрим что
# исходя из параметров пациенты скорей всего заболеют, т.е.
# их можно отнести к группе риска

In [ ]:
Y_pred

array([5713,  627, 5450, 5888, 5450, 5713, 5713, 5713, 4770, 4770, 6057,
       5713, 5713, 5713, 5713,  367,  367,  324,  367,  324,  324,  769,
        769,  367, 5713, 5713, 5713, 5713, 5713, 4770, 6057, 2929, 5713,
       5713, 5713,  367,  367,  367,  367,  367,  367,  367,  367,  367,
        367, 5713, 5713, 5713, 5713, 5713, 5713, 4770, 4770, 5713, 5713,
       5713, 5888, 5888, 5888,  627,  367,  367,  627,  730,  730, 5330,
        627,  627, 5330, 5330, 5030, 5330, 2777, 2450, 2450, 2450, 2450,
       2450, 1671, 2450, 2450,  432,  432,  730,  432,  411,  265,  265,
        265,  265, 2929, 2929, 5669, 5067, 5067, 5067, 2450, 2450, 2450,
       2450, 2450, 2450, 2450, 1671,  432,  730,  730,  380,  730, 5330,
        411,  411, 5403, 5330, 5330, 5330, 5330, 5330, 2450, 2450, 2450,
       2450, 1671, 2450, 1671, 2929,  411,  411,  265,  265,  265,  265,
        411,  411,  411,  411, 2929, 2929, 4887, 5713, 5713, 5713, 5713,
       2450, 2450, 2929, 1693, 1693,  959,  959,  3

In [ ]:
Y

array([5545, 4516, 4767, 5026, 4918, 5181, 5584, 6015, 5791, 4770, 3539,
       2784, 2361, 1529,  963,  506,  321,  273,  367,  814, 2718, 5673,
       6511, 5471, 5097, 4887, 5337, 5692, 6137, 4623, 3591, 2898, 2637,
       1777, 1015,  598,  369,  312,  367,  835, 2726, 5689, 6990, 5985,
       5309, 4603, 4884, 5104, 5178, 5501, 5713, 6292, 6057, 4907, 3503,
       3037, 2822, 1992, 1166,  627,  388,  368, 2489, 5537, 6628, 5534,
       5403, 4770, 5217, 5870, 5967, 6108, 6128, 6069, 6169, 5384, 4063,
       3364, 2971, 2450, 1832, 1231,  718,  545,  411,  688, 1352, 2072,
       3342, 4258, 4861, 5191, 5669, 5074, 5025, 5153, 5024, 4779, 4362,
       3860, 3160, 2992, 3202, 1941, 1233,  323,  312,  627, 1508, 1539,
       2232, 4568, 4624, 4529, 5139, 6640, 6589, 4429, 4329, 3833, 4015,
       3382, 2815, 2110, 1555,  959,  455,  336,  265,  314,  779, 2571,
       5563, 6676, 5966, 4832, 4395, 4411, 4648, 4602, 5125, 5502, 5979,
       5663, 4259, 3069, 2378, 2030, 1400,  917,  5

In [ ]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
R2=r2_score(Y, Y_pred)
R2

-0.03994768116315717

**вводим конкретные данные:**

In [ ]:
x_new=np.array([[14.88,14.57,0.88,5.55,3.33,1.02,4.96	],[11.23,12.88,0.85,5.14,2.79,4.33,5.00	]])
# это данные 2-х пациентов щас проверим заболеют или нет

In [ ]:
model.predict(x_new) # сюда заносим конкретные данные и смотрим прогноз

array([1., 3.])

**13. По обученной модели дайте прогноз вероятности классов для новых наблюдений, воспользовавшись функцией predict_proba().**

In [ ]:
model.predict_proba(x_new)
# нулевой столбец - это нулевой класс
# первый столбец - это первый класс
# первая строка - это первые данные (здесь с вероятностью 96% относится к 1-ому типу)
# вторая строка = это вторые данные (здесь с вероятностью 83% относится к 3-ему типу)

array([[0.95628385, 0.0423319 , 0.00138425],
       [0.1642972 , 0.00303227, 0.83267053]])

# **ЛОГИСТИЧЕСКАЯ РЕГРЕССИЯ (на стандартизированных данных)**

________________________________________________________________________________

# **НАЧАЛО**
# **стандартизируем, удаляем выбросы:**

1. Масштабируем
2. Стандартизируем
3. Заменяем выбросы на NaN (больше 3-х стандартных отклонений)
4. NaN были заменены на соседнее число **Текст, выделенный полужирным шрифтом**

DataFrame.values Pandas DataFrame.values возвращает Numpy-представление данного DataFrame.
Используйте атрибут DataFrame.values чтобы возвратить пустое представление данного DataFrame.

In [ ]:
X.shape

(210, 7)

**масштабирование:**

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
from pandas.core.apply import FrameApply
scaler=MinMaxScaler(feature_range=(0,1))

In [ ]:
rescaledX=scaler.fit_transform(X)
rescaledX

In [ ]:
from numpy import set_printoptions

In [ ]:
set_printoptions(precision=4)

In [ ]:
rescaledX

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler=StandardScaler().fit(X) # создаем объект и обучаем

In [ ]:
rescaledX=scaler.transform(X) # преобразуем данные

In [ ]:
rescaledX[:5,:]

In [ ]:
import pandas as pd
fg = pd.DataFrame(rescaledX)
fg.head(15)

In [ ]:
import numpy as np

**цикл который меняет выбросы (значения превышающие 3 стандартных отклонения) на NaN во всех столбцах:**

In [ ]:
for i in fg:
    fg[i] = np.where((fg[i] > 3) | (fg[i] < -3), np.nan, fg[i])
fg.head(15)

In [ ]:
fgY = pd.DataFrame(Y)
fgY.head(5)

In [ ]:
fg['end'] = fgY

In [ ]:
fg.head(5)

In [ ]:
fg_groupby = fg.sort_values(by=['end',3]) # упорядочиваем данные по результирующим признакаам

In [ ]:
fg_groupby.isna().sum()

In [ ]:
fg_groupby['end'].value_counts()

In [ ]:
fg_groupby.head(20)

In [ ]:
fg_groupby = fg_groupby.fillna(method ='pad') # заменяем NaN на предыдущее значение в столбце
# методы Значение параметра метода: {‘pad’, ‘ffill’,‘backfill’, ‘bfill’, None}, default None
#pad/ffill: использование предыдущий Не пропущенное значение, чтобы заполнить пропущенное значение
#backfill/bfill: использование следующий Заполните пропущенное значение не пропущенным значением
#None: Укажите значение для замены отсутствующего значения (по умолчанию это так)

In [ ]:
df

area_A  perimeter_P  compactness  length_of_ker  width_of_ker  asymmetry_coeff  \
0     15.26        14.84         0.87           5.76          3.31             2.22   
1     14.88        14.57         0.88           5.55          3.33             1.02   
2     14.29        14.09         0.91           5.29          3.34             2.70   
3     13.84        13.94         0.90           5.32          3.38             2.26   
4     16.14        14.99         0.90           5.66          3.56             1.35   
..      ...          ...          ...            ...           ...              ...   
205   12.19        13.20         0.88           5.14          2.98             3.63   
206   11.23        12.88         0.85           5.14          2.79             4.33   
207   13.20        13.66         0.89           5.24          3.23             8.31   
208   11.84        13.21         0.85           5.17          2.84             3.60   
209   12.30        13.34         0.87           5.24          2.97             5.64   

     length_of_ker_groove  class class_name  
0                    5.22      1       Кама  
1                    4.96      1       Кама  
2                    4.83      1       Кама  
3                    4.80      1       Кама  
4                    5.17      1       Кама  
..                    ...    ...        ...  
205                  4.87      3  Канадская  
206                  5.00      3  Канадская  
207                  5.06      3  Канадская  
208                  5.04      3  Канадская  
209                  5.06      3  Канадская  

[210 rows x 9 columns]

In [ ]:
fg_groupby.head(5)

0         1         2     3     4     5     6  end
0  0.14  2.15e-01  6.06e-05  0.30  0.14 -0.99 -0.38  1.0
1  0.01  8.22e-03  4.29e-01 -0.17  0.20 -1.79 -0.92  1.0
2 -0.19 -3.60e-01  1.44e+00 -0.76  0.21 -0.67 -1.19  1.0
3 -0.35 -4.75e-01  1.04e+00 -0.69  0.32 -0.96 -1.23  1.0
4  0.45  3.31e-01  1.37e+00  0.07  0.81 -1.56 -0.48  1.0

In [ ]:
fg_groupby.isna().sum()

In [ ]:
fg_groupby = fg_groupby.sort_index()

In [ ]:
fg_groupby['end'] = fg_groupby['end'].astype('int')

In [ ]:
fg_groupby.dtypes

0      float64
1      float64
2      float64
3      float64
4      float64
5      float64
6      float64
end      int64
dtype: object