In [1]:
import pandas as pd
import numpy as np
from pandas import read_csv

**1.1_Загрузка_данных**

In [11]:
df_1=read_csv('D:\_ДАННЫЕ\Train_cleared_fillna.csv')

In [12]:
df_1=df_1.filter(regex='^(?!.*Unnamed).*$')

In [13]:
df_1.shape

(8067, 10)

In [5]:
# 1.1.2 Данные с заполнением NaN соседними данными после группировки (fillna) без удаления строк.

In [6]:
df_test=read_csv('D:\_ДАННЫЕ\Test_CLEARED_END!!!!!!!!.csv')

In [8]:
df_test=df_test.filter(regex='^(?!.*Unnamed).*$')

In [10]:
df_test.shape

(2032, 10)

In [14]:
df = pd.concat([df_1,df_test],axis=0)

In [15]:
df.shape

(10099, 10)

In [17]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier
from sklearn.svm import SVC

In [18]:
def to_array(x):
    array = x.values
    X = array[:,0:9]
    Y = array[:,9]
    return [X,Y]


In [19]:
X = to_array(df)[0]
Y = to_array(df)[1]

In [22]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, shuffle=True, random_state=7)

In [ ]:
pd.DataFrame(X_train)

In [29]:
df_train_1 = pd.concat([pd.DataFrame(X_train, columns={'Пол', 'Семейное_положение',
                   'Возраст', 'Высшее_образование',
                   'Профессия', 'Опыт_работы',
                   'Уровень_расходов', 'Размер_семьи',
                   'Анонимная_категория'
                  }),pd.DataFrame(Y_train,columns={'Целевая_категория'})],axis=1)

In [30]:
df_train_1

Анонимная_категория  Семейное_положение  Опыт_работы  Возраст  Пол  \
0                     1.0                 1.0         71.0      0.0  7.0   
1                     1.0                 1.0         66.0      0.0  8.0   
2                     0.0                 1.0         38.0      1.0  1.0   
3                     0.0                 0.0         25.0      0.0  9.0   
4                     1.0                 1.0         51.0      1.0  7.0   
...                   ...                 ...          ...      ...  ...   
7569                  0.0                 0.0         40.0      0.0  4.0   
7570                  0.0                 1.0         38.0      1.0  5.0   
7571                  0.0                 1.0         74.0      1.0  6.0   
7572                  1.0                 0.0         35.0      1.0  3.0   
7573                  1.0                 1.0         53.0      0.0  7.0   

      Уровень_расходов  Размер_семьи  Высшее_образование  Профессия  \
0                  5.0           3.0                 3.0        4.0   
1                  1.0           3.0                 4.0        6.0   
2                  1.0           2.0                 4.0        3.0   
3                  1.0           3.0                 7.0        4.0   
4                  1.0           3.0                 3.0        6.0   
...                ...           ...                 ...        ...   
7569               8.0           3.0                 1.0        6.0   
7570               7.0           1.0                 4.0        3.0   
7571              12.0           1.0                 2.0        6.0   
7572               1.0           3.0                 3.0        3.0   
7573               2.0           1.0                 4.0        4.0   

      Целевая_категория  
0                   2.0  
1                   4.0  
2                   3.0  
3                   2.0  
4                   3.0  
...                 ...  
7569                1.0  
7570                3.0  
7571                3.0  
7572                1.0  
7573                1.0  

[7574 rows x 10 columns]

In [31]:
df_test_1 = pd.concat([pd.DataFrame(X_test, columns={'Пол', 'Семейное_положение',
                   'Возраст', 'Высшее_образование',
                   'Профессия', 'Опыт_работы',
                   'Уровень_расходов', 'Размер_семьи',
                   'Анонимная_категория'
                  }),pd.DataFrame(Y_test,columns={'Целевая_категория'})],axis=1)

In [32]:
df_test_1

Анонимная_категория  Семейное_положение  Опыт_работы  Возраст  Пол  \
0                     1.0                 1.0         35.0      1.0  1.0   
1                     0.0                 1.0         52.0      1.0  1.0   
2                     0.0                 1.0         69.0      1.0  4.0   
3                     0.0                 0.0         40.0      0.0  1.0   
4                     1.0                 1.0         84.0      1.0  6.0   
...                   ...                 ...          ...      ...  ...   
2520                  1.0                 1.0         42.0      1.0  1.0   
2521                  0.0                 1.0         48.0      1.0  1.0   
2522                  0.0                 1.0         47.0      1.0  5.0   
2523                  1.0                 1.0         55.0      1.0  1.0   
2524                  0.0                 1.0         39.0      0.0  3.0   

      Уровень_расходов  Размер_семьи  Высшее_образование  Профессия  \
0                  2.0           2.0                 3.0        6.0   
1                  3.0           3.0                 2.0        4.0   
2                  0.0           3.0                 2.0        4.0   
3                  0.0           3.0                 1.0        5.0   
4                  0.0           1.0                 2.0        6.0   
...                ...           ...                 ...        ...   
2520               1.0           3.0                 4.0        4.0   
2521               3.0           3.0                 1.0        6.0   
2522               1.0           2.0                 4.0        6.0   
2523               0.0           1.0                 2.0        3.0   
2524               0.0           3.0                 4.0        4.0   

      Целевая_категория  
0                   3.0  
1                   2.0  
2                   2.0  
3                   1.0  
4                   1.0  
...                 ...  
2520                2.0  
2521                1.0  
2522                3.0  
2523                1.0  
2524                1.0  

[2525 rows x 10 columns]

In [ ]:
=============================================================================================================

In [34]:
import pandas as pd
import numpy as np
from pandas import read_csv

In [2]:
df=read_csv('D:\Политех\Класиффикация\Сегментация_клиентов\Train_cleared_!!!!!!!!.csv')

In [3]:
df=df.filter(regex='^(?!.*Unnamed).*$')

In [4]:
df_T=read_csv('D:\Политех\Класиффикация\Сегментация_клиентов\Test_cleared_!!!!!!!!.csv')

In [5]:
df_T=df_T.filter(regex='^(?!.*Unnamed).*$')

**Обучающий_набор**

In [35]:
array = df_train_1.values
array
X = array[:,0:9]
Y = array[:,9]

**Тестовый_набор**

In [36]:
array_T = df_test_1.values
array_T
XX = array_T[:,0:9]
YY = array_T[:,9]

In [37]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
# отбор признаков:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
# ансамблевые функции:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
import numpy as np
from sklearn.linear_model import RidgeClassifier
from sklearn.model_selection import GridSearchCV
from scipy.stats import uniform
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import train_test_split
# сохраняет параметры после перезагрузки:
import pickle
import joblib

In [ ]:
========================================================================================================================

In [ ]:
========================================================================================================================

# **GrideSearchCV**

In [39]:
from sklearn.model_selection import GridSearchCV
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor

In [40]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, shuffle=True, random_state=7) 

In [41]:
clf = RandomForestClassifier()

In [42]:
params = {'n_estimators': range (10, 250, 10),
          'max_depth': range (1,13, 2),
          'min_samples_leaf': range (1,8),
          'min_samples_split': range (2,10,2) }

In [43]:
grid = GridSearchCV(clf, param_grid = params, cv=3,verbose=1,n_jobs=-1)

In [44]:
grid.fit(X_train,Y_train)

Fitting 3 folds for each of 4032 candidates, totalling 12096 fits


KeyboardInterrupt: 

In [16]:
print(grid.best_params_)
print(grid.best_estimator_)

{'max_depth': 7, 'min_samples_leaf': 3, 'min_samples_split': 2, 'n_estimators': 60}
RandomForestClassifier(max_depth=7, min_samples_leaf=3, n_estimators=60)


In [50]:
from sklearn.metrics import classification_report, confusion_matrix

In [18]:
grid_predictions = grid.predict(X_test)
print(classification_report(Y_test, grid_predictions))

              precision    recall  f1-score   support

         1.0       0.46      0.48      0.47       351
         2.0       0.40      0.34      0.37       347
         3.0       0.56      0.53      0.55       361
         4.0       0.59      0.68      0.63       373

    accuracy                           0.51      1432
   macro avg       0.50      0.51      0.50      1432
weighted avg       0.51      0.51      0.51      1432



In [19]:
print(confusion_matrix(Y_test, grid_predictions))

[[169  73  39  70]
 [ 78 119 103  47]
 [ 32  78 192  59]
 [ 85  29   7 252]]


In [ ]:
================================================================================================================

In [45]:
model = RandomForestClassifier(max_depth=7, min_samples_leaf=3, n_estimators=60)

In [46]:
model.fit(X_train,Y_train)

RandomForestClassifier(max_depth=7, min_samples_leaf=3, n_estimators=60)

In [47]:
new_predictions = model.predict(X_test)

In [51]:
print(classification_report(Y_test, new_predictions))
print(confusion_matrix(Y_test, new_predictions))

              precision    recall  f1-score   support

         1.0       0.40      0.47      0.43       488
         2.0       0.37      0.25      0.30       448
         3.0       0.53      0.53      0.53       433
         4.0       0.57      0.62      0.60       525

    accuracy                           0.48      1894
   macro avg       0.47      0.47      0.46      1894
weighted avg       0.47      0.48      0.47      1894

[[230  91  64 103]
 [133 114 113  88]
 [ 76  71 230  56]
 [134  32  31 328]]


In [ ]:
================================================================================================================

In [24]:
kfold=KFold(n_splits=3,random_state=7,shuffle=True)
results=cross_val_score(model, X, Y, cv=3)
results.mean()

0.5112624410686224